import Image from 'next/image';

export default function GratingApplicationCards() {
  const items = [
    { image: '/images/products/molded-frp-grating/molded-grating-coastal-walkway.webp', title: 'Wet & coastal access', body: 'Begin with drainage, top opening and the walking surface. Include exposure and cleaning requirements.', points: ['Surface and footwear', 'Clear opening', 'Support layout'], href: '#grating-help', action: 'Explore selection requirements' },
    { image: '/images/products/pultruded-frp-grating/pultruded-grating-rooftop-walkway.webp', title: 'Platforms & maintenance walkways', body: 'Start with the support arrangement and bearing direction. Mark access openings and finished panel sizes.', points: ['Clear span and loads', 'Bearing-bar direction', 'Cutting and fixing scope'], href: '#grating-review', action: 'Prepare an engineering review' },
  ];
  return <section className="bg-white py-12"><div className="site-container"><p className="text-xs font-bold uppercase tracking-widest text-teal-text">Start with the job</p><h2 className="mt-3 text-3xl font-bold">What does your walking surface need to do?</h2><div className="mt-6 grid gap-6 md:grid-cols-2">{items.map(item => <article key={item.title} className="overflow-hidden rounded-card border border-border-default"><div className="relative aspect-[16/7]"><Image src={item.image} alt={`${item.title} — application reference`} fill sizes="(max-width:767px) 94vw, 46vw" className="object-cover" /></div><div className="p-6"><p className="text-xs text-t3">Application reference · project specifications vary</p><h3 className="mt-2 text-xl font-bold">{item.title}</h3><p className="mt-3 text-sm leading-relaxed text-t2">{item.body}</p><ul className="my-4 flex flex-wrap gap-2">{item.points.map(p => <li key={p} className="rounded-full bg-bg2 px-3 py-2 text-xs font-semibold">{p}</li>)}</ul><a className="inline-flex min-h-11 items-center text-sm font-bold text-teal-text" href={item.href}>{item.action} →</a></div></article>)}</div></div></section>;
}
