import { evidenceRevision } from "@/content/data/engineeringEvidence";
import { reportVerifications, verificationPath } from "@/content/data/reportVerification";
import type { MetadataRoute } from "next";
import { blogPosts } from "@/content/data/blogPosts";
import { applicationPages } from "@/lib/applicationPages";
import { specialistProductIndex } from "@/content/data/pultrusionGuideIndex";
import { pultrusionGuideReviewed } from "@/content/data/pultrusionGuideTypes";
import { performanceReviewed } from "@/content/data/pultrudedPerformance";
import { INDEXED_DATASHEET_SLUGS } from "@/lib/datasheetContent";

const BASE = "https://www.f1composite.com";

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const latestBlogUpdate =
    [...blogPosts]
      .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0]
      ?.updatedAt ?? "2026-04-02";

  const blogEntries = blogPosts.map((post) => ({
    url: `${BASE}/resources/blog/${post.slug}`,
    lastModified: post.updatedAt,
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  // Datasheet indexing pilot: only these sizes are indexable (lib/datasheetContent.ts).
  const datasheetEntries = INDEXED_DATASHEET_SLUGS.map((slug) => ({
    url: `${BASE}/datasheets/${slug}`,
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  const applicationEntries = applicationPages.map((page) => ({
    url: `${BASE}/applications/${page.slug}`,
    lastModified: page.lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.78,
  }));

  // Only content records with a real, content-owned update field emit
  // <lastmod>. Static routes intentionally omit it: a guessed or deploy-time
  // date is less useful than no date and quickly becomes inaccurate.
  return [
    ...specialistProductIndex.map((page) => ({ url: `${BASE}/products/${page.slug}`, lastModified: pultrusionGuideReviewed, changeFrequency: "monthly" as const, priority: 0.75 })),
    { url: `${BASE}/sourcing/equipment`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/materials`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/pultrusion-machines`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/pultrusion-dies`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/resin-mixing-injection`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/pullwinding-equipment`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/slitting-cutting-equipment`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/smc-production-lines`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/bmc-smc-molds`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/fiberglass-direct-roving`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/fiberglass-mat-veil`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/stitched-fiberglass-fabrics`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/sourcing/gelcoat-resins`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.7 },

    { url: `${BASE}/products/fiberglass-square-rods`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/products/fiberglass-t-profiles`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/products/frp-sheet-piling`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/products/frp-rock-bolts`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/products/frp-fencing`, lastModified: "2026-10-02", changeFrequency: "monthly", priority: 0.75 },

    { url: BASE, changeFrequency: "weekly", priority: 1.0 },
    { url: `${BASE}/technology/pultruded-profile-performance`, lastModified: performanceReviewed, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/pultruded-frp-profiles`, changeFrequency: "weekly", priority: 0.95 },
    { url: `${BASE}/what-is-frp`, lastModified: "2026-09-14", changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/products/window-door-profiles`, lastModified: "2026-09-12", changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/fiberglass-door-thresholds`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/products/frp-door-frames`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/fiberglass-windows-doors`, lastModified: "2026-09-12", changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/grating`, lastModified: "2026-09-20", changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/industries/water-wastewater`, lastModified: "2026-09-12", changeFrequency: "monthly", priority: 0.8 },
    // /products permanently redirects to /products/product-lines (see next.config.ts)
    { url: `${BASE}/products/fiberglass-structural-shapes`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/tools`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/tools/profile-finder`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/tools/thermal-expansion-calculator`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/tools/handrail-load-calculator`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/tools/access-geometry-checker`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/tools/gfrp-rebar-calculator`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/tools/frp-cut-list-optimizer`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/tools/frp-column-calculator`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/tools/frp-unit-converter`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/tools/frp-life-cycle-cost-calculator`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/products/fiberglass-structural-shapes/frp-i-beam`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/products/fiberglass-structural-shapes/frp-angle`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/products/fiberglass-structural-shapes/frp-channel`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/products/fiberglass-structural-shapes/frp-square-tube`, lastModified: "2026-09-14", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/products/fiberglass-structural-shapes/frp-tube`, lastModified: "2026-09-14", changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/products/fiberglass-structural-shapes/frp-flat-bar`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/products/fiberglass-structural-shapes/frp-rod`, changeFrequency: "monthly", priority: 0.7 },
    ...datasheetEntries,
    { url: `${BASE}/products/frp-rebar`, lastModified: "2026-09-21", changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE}/products/frp-fasteners-fittings`, lastModified: "2026-09-21", changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE}/products/fiberglass-snow-markers`, changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE}/products/fiberglass-stakes`, changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE}/products/custom-pultruded-profiles`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/fiberglass-dog-bone`, changeFrequency: "monthly", priority: 0.78 },
    { url: `${BASE}/products/frp-pultrusion-manufacturer-factory-direct`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/products/frp-solar-mounting-systems`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/products/frp-window-frames`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/frp-facade-panels`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/frp-window-reinforcement`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/products/frp-sound-barrier-wall`, changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE}/technology/china-alternative-to-tencom-creative-pultrusions-windows`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/products/frp-gratings`, lastModified: "2026-09-20", changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/frp-deck-panels`, changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE}/products/molded-frp-grating`, lastModified: "2026-09-20", changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE}/products/frp-stair-treads`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/frp-ladders`, changeFrequency: "monthly", priority: 0.82 },
    { url: `${BASE}/products/frp-handrail-systems`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/fiberglass-sheets`, lastModified: "2026-09-14", changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/fiberglass-plates`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/products/wind-turbine-blade-panels`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/products/product-lines`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/technology`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/technology/pultrusion-process`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/technology/pultrusion-resin-systems`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/technology/frp-vs-traditional-materials`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/technology/frp-vs-aluminum-windows`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/technology/fiberglass-rebar-vs-steel`, lastModified: "2026-09-21", changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/technology/frp-vs-steel-gratings`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/technology/frp-vs-pvc-windows`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/technology/china-alternative-to-strongwell-fiberline-exel`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/technology/pultrusion-vs-extrusion-filament-winding`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/technology/polyurethane-pultrusion-windows`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/technology/quality-testing`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/technology/knowhow-services`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/frp-density-calculator`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/frp-profile-calculator`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/frp-profile-calculator/methodology`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/frp-profile-calculator/validation`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/frp-span-tables`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/fiberglass-pultruded-profile-price`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/technology/frp-u-value-calculator`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/industries`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/industries/construction`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/industries/infrastructure`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/industries/energy`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/industries/marine`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/industries/industrial`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/industries/vehicle`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/applications`, changeFrequency: "monthly", priority: 0.85 },
    ...applicationEntries,
    { url: `${BASE}/case-studies`, changeFrequency: "weekly", priority: 0.8 },
    {
      url: `${BASE}/case-studies/beam-bridge`,
      lastModified: "2026-09-08",
      changeFrequency: "monthly",
      priority: 0.9,
      images: [
        `${BASE}/images/case-studies/beam-bridge/pedestrian-cycle-beam-bridge-load-path.svg`,
        `${BASE}/images/case-studies/beam-bridge/pedestrian-cycle-bridge-section.svg`,
        `${BASE}/images/case-studies/beam-bridge/footbridge-vibration-serviceability.svg`,
        `${BASE}/images/case-studies/beam-bridge/moggill-road-cycle-bridge-case-study.svg`,
        `${BASE}/images/case-studies/beam-bridge/coronation-drive-frp-cycleway-case-study.svg`,
        `${BASE}/images/case-studies/beam-bridge/sao-silvestre-gfrp-footbridge-case-study.svg`,
      ],
    },
    { url: `${BASE}/case-studies/european-bridge-deck`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/case-studies/coastal-marina-walkway`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/case-studies/baotou-industrial-gfrp-pu-windows`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/case-studies/wanhua-yantai-zero-carbon-windows`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/case-studies/chongqing-rooftop-pv-frp-rail`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/case-studies/water-treatment-cable-tray`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/case-studies/qinling-station-antarctic-passive-windows`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/case-studies/yancheng-talent-apartment-fenestration`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/case-studies/factory-access-staircase`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/resources`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE}/resources/evidence`, lastModified: evidenceRevision, changeFrequency: "monthly", priority: 0.8 },
    ...reportVerifications.map((item) => ({ url: `${BASE}${verificationPath(item.slug)}`, lastModified: evidenceRevision, changeFrequency: "monthly" as const, priority: 0.6 })),
    { url: `${BASE}/resources/technical-data`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/resources/how-to-choose-frp-pultrusion-supplier`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE}/resources/frp-windows-guide`, changeFrequency: "weekly", priority: 0.85 },
    { url: `${BASE}/resources/frp-pultrusion-fob-ddp-export-guide`, changeFrequency: "monthly", priority: 0.78 },
    { url: `${BASE}/resources/design-guides`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE}/resources/glossary`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/resources/blog`, lastModified: latestBlogUpdate, changeFrequency: "weekly", priority: 0.7 },
    ...blogEntries,
    { url: `${BASE}/resources/downloads`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE}/about`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE}/about/authors`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/about/authors/yifan-liu`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE}/about/authors/haifeng-gong`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE}/about/authors/duowei-wang`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE}/ask`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/ai/sourcing`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/ai/passive-house`, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/regions`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/regions/frp-grating-supplier-saudi-arabia`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/regions/pultruded-frp-solar-mounting-australia`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/regions/frp-cable-tray-uae-oil-gas`, changeFrequency: "monthly", priority: 0.85 },
    { url: `${BASE}/regions/frp-pultrusion-supplier-usa`, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/regions/frp-passive-house-windows-canada`, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/regions/frp-passive-house-windows-germany`, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/regions/grp-windows-uk`, changeFrequency: "monthly", priority: 0.92 },
    { url: `${BASE}/contact`, changeFrequency: "yearly", priority: 0.8 },
  ];
}
