import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import PageHeader from "@/components/layout/PageHeader";
import FAQ from "@/components/ui/FAQ";
import JsonLd from "@/components/seo/JsonLd";
import JumpNav from "@/components/sections/JumpNav";
import WindowSystemExplorer from "@/components/sections/WindowSystemExplorer";
import { WindowSupplyRoutes, WindowComponentMap, WindowBuyerPaths, WindowEvidenceCards, WindowPurchaseFlow, WindowScopeTable, windowWrap } from "@/components/sections/WindowBuyingGuide";
import { buildPageMetadata, buildProductFamilyPageSchema } from "@/lib/seo";
import { buildWindowRfqHref } from "@/lib/windowInquiry";

const pagePath = "/products/frp-window-frames";
const description = "Compare nine FRP window and door systems. Source fiberglass profiles for local fabrication or finished units, with separate procurement guides and RFQs.";
export const metadata: Metadata = buildPageMetadata({ title: "FRP Window Frames & System Profiles | F1 Composite", description, path: pagePath, image: "/products/frp-window-frames/opengraph-image" });
const faq = [
  { question: "Do you sell FRP profiles or finished windows and doors?", answer: "Both, through separate supply routes. Choose system profiles when you will fabricate locally. Choose finished units when you need an agreed assembly built to a window schedule. Glass, hardware, accessories, machining, packing and delivery are defined in the quotation." },
  { question: "What are fiberglass window lineals?", answer: "Lineals are the pultruded profile lengths used to make the window frame, sash, mullion and other constant-section components. A compatible set of lineals and accessories is cut, joined, glazed and fitted with hardware to form a finished window." },
  { question: "Which window and door systems are available for review?", answer: "The catalog covers 50, 55, 60, 65, 70, 80 and 90 casement systems, a distinct 90 sliding system, and the 140 compression-seal sliding door. Review the current section drawings, opening configuration and supply availability before ordering." },
  { question: "Is the 140 series a lift-and-slide door?", answer: "The current 140 range is a compression-seal (side-pressure) sliding door system, with section references CP006–CP011. The historical Intertek lift-sliding report retains its original specimen name. Its results do not automatically apply to the current compression-seal configuration." },
  { question: "Can the same U-value be used for every size and series?", answer: "No. Uf describes the frame, Ug the glazing and Uw the whole window. Window size, frame, glass, spacer and assembly affect the result. The 90-series PHI certificate covers its stated configuration, not every unit assembled from FRP profiles." },
  { question: "What should I send if I do not have complete drawings?", answer: "Start with your role, destination, intended opening or application and expected quantity if known. Choose technical selection, budget pricing or sample evaluation. We can clarify the section list or window schedule before a formal quote." },
  { question: "What determines price, minimum quantity and delivery timing?", answer: "For profiles, review the section, lengths, material, finish, quantity, tooling and machining. For finished units, review each opening, glass and hardware configuration. Packing, transport, testing, sample fees, production quantity and lead time are confirmed for the order; a catalog listing is not a stock promise." },
  { question: "Who handles local installation and warranty?", answer: "Agree installation information, local labor, unloading, spare parts and after-sales responsibilities in the supply scope. Warranty terms depend on the contracted product and configuration. Shipping complete units does not by itself include on-site installation." },
];

export default function FenestrationSystemsPage() {
  return <>
    <JsonLd data={buildProductFamilyPageSchema({ name: "FRP Window Frames & Door System Profiles", description, path: pagePath, image: "/images/products/window-systems/70.jpg", category: "Windows & Doors", productLine: "F1-THERM", schemaType: "CollectionPage", datePublished: "2026-04-04", dateModified: "2026-09-20", additionalProperty: [{ name: "Supply routes", value: "System profiles for local fabrication; finished windows and doors" }, { name: "Systems", value: "50, 55, 60, 65, 70, 80, 90 casement, 90 sliding, 140 compression-seal sliding" }, { name: "Current sliding profile references", value: "90 sliding CP001–CP005; 140 compression-seal CP006–CP011" }] })} />
    <PageHeader tag="Windows & Doors · F1-THERM" title="FRP window & door systems" description="Pultruded fiberglass system profiles for local fabrication, with finished windows and doors available for project supply. Find your series, define the scope and start the right conversation." breadcrumbs={[{ label: "Home", href: "/" }, { label: "Products", href: "/products/product-lines" }, { label: "Windows & Doors" }]} actions={{ primary: { label: "Request a Profile Quote", href: buildWindowRfqHref({ mode: "profiles", source: "window-hub-hero", productPath: pagePath }) }, secondary: { label: "Request a Finished-Unit Quote", href: buildWindowRfqHref({ mode: "finished", source: "window-hub-hero", productPath: pagePath }) }, note: "Start with your name and email · Technical details can follow", stickyMobile: true }} />
    <section id="supply" className="bg-white py-9"><div className={windowWrap}><WindowSupplyRoutes /></div></section>
    <JumpNav items={[{ href: "#series", label: "Compare systems" }, { href: "#frames-profiles", label: "System components" }, { href: "#buyers", label: "Your buying path" }, { href: "#procurement", label: "Procurement" }, { href: "#evidence", label: "Evidence & resources" }, { href: "#faq", label: "Questions" }]} />
    <section id="series" className="bg-bg2 py-14"><div className={windowWrap}><p className="text-xs font-bold uppercase tracking-widest text-teal-text">From opening type to profile set</p><h2 className="mt-3 text-3xl font-bold text-t1">Find your starting system</h2><p className="mb-7 mt-4 max-w-3xl text-t2">Compare casement, tilt-and-turn, sliding and compression-seal systems. Review the matching sections before requesting samples or a quotation. For assembled units, use the finished-window route.</p><WindowSystemExplorer productPath="/products/frp-window-frames" /><Link href="/products/fiberglass-windows-doors#series" className="mt-7 inline-block py-2 text-sm font-bold text-teal-text">Compare these systems for finished-unit supply →</Link></div></section>
    <section id="frames-profiles" className="bg-white py-14"><div className={windowWrap}><WindowComponentMap /><div className="mt-10"><WindowScopeTable /></div></div></section>
    <section id="buyers" className="bg-bg2 py-14"><div className={windowWrap}><p className="text-xs font-bold uppercase tracking-widest text-teal-text">Six buying situations</p><h2 className="mb-7 mt-3 text-3xl font-bold text-t1">Find the path that fits your work</h2><WindowBuyerPaths /></div></section>
    <section id="procurement" className="bg-white py-14"><div className={windowWrap}><h2 className="text-3xl font-bold text-t1">Know the steps before you place an order</h2><div className="mt-7"><h3 className="mb-5 text-xl font-bold text-teal-text">01 · Profiles for local fabrication</h3><WindowPurchaseFlow mode="profiles" compact /><Link href="/products/window-door-profiles#procurement" className="mt-5 inline-block py-2 text-sm font-bold text-teal-text">See the inputs and confirmation points →</Link></div><div className="mt-10 border-t border-border-default pt-9"><h3 className="mb-5 text-xl font-bold text-teal-text">02 · Finished windows &amp; doors</h3><WindowPurchaseFlow mode="finished" compact /><Link href="/products/fiberglass-windows-doors#procurement" className="mt-5 inline-block py-2 text-sm font-bold text-teal-text">See the project procurement guide →</Link></div></div></section>
    <section id="evidence" className="bg-bg2 py-14"><div className={windowWrap}><p className="text-xs font-bold uppercase tracking-widest text-teal-text">Make an informed specification</p><h2 className="mb-7 mt-3 text-3xl font-bold text-t1">Match the evidence to the proposed assembly</h2><WindowEvidenceCards /><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Nine-series catalog", "Series, section references, procurement and supply scope.", "/downloads/f1composite-frp-window-door-catalog.pdf", "Download PDF"], ["Profile BOM template", "Organize sections, cut lengths, units and accessories.", "/downloads/f1-window-profile-bom-template.csv", "Download CSV"], ["Window schedule template", "Organize opening IDs, size basis, configurations and quantities.", "/downloads/f1-window-schedule-template.csv", "Download CSV"]].map(([title, text, href, action]) => <article className="rounded-xl border border-border-default bg-white p-5" key={title}><h3 className="font-bold text-t1">{title}</h3><p className="mt-2 text-sm text-t2">{text}</p><Link href={href} className="mt-4 inline-block py-2 text-sm font-bold text-teal-text">{action} →</Link></article>)}</div><div className="mt-7 flex flex-wrap gap-x-8"><Link href="/resources/frp-windows-guide" className="inline-block py-2 text-sm font-bold text-teal-text">Explore the FRP window materials, fabrication and buying guide →</Link><Link href="/technology/polyurethane-pultrusion-windows" className="inline-block py-2 text-sm font-bold text-teal-text">Polyurethane pultrusion windows →</Link><Link href="/products/frp-door-frames" className="inline-block py-2 text-sm font-bold text-teal-text">FRP door frame profiles →</Link></div></div></section>
    <section className="bg-white py-12"><div className={`${windowWrap} grid gap-8 lg:grid-cols-2`}><div className="relative min-h-64 overflow-hidden rounded-2xl"><Image src="/images/case-studies/frp-fenestration-residential-tower-facade.jpg" alt="Residential building facade used as a fenestration application reference" fill sizes="(max-width: 1024px) 90vw, 44vw" className="object-cover" /></div><div className="py-3"><p className="text-xs font-bold uppercase tracking-widest text-teal-text">Applications &amp; project context</p><h2 className="mt-3 text-3xl font-bold text-t1">Connect the system to the building</h2><p className="mt-4 text-sm leading-relaxed text-t2">Residential, education, healthcare and industrial projects can require different opening arrangements, glass, hardware and installation details. Use manufacturing-partner project references to start a discussion about your own specification.</p><p className="mt-4 text-xs text-t3">An application or project reference does not establish performance for a different assembly. Confirm the supply role and relevant documents for your project.</p><div className="mt-5 flex flex-wrap gap-5"><Link href="/case-studies" className="py-2 text-sm font-bold text-teal-text">Explore project references →</Link><Link href="/industries/construction" className="py-2 text-sm font-bold text-teal-text">Building applications →</Link></div></div></div></section>
    <section id="faq" className="bg-bg2 py-14"><div className={windowWrap}><h2 className="mb-6 text-3xl font-bold text-t1">Before you request a quote</h2><FAQ items={faq} /><div className="mt-10 rounded-2xl bg-deep p-7 text-white md:p-9"><h2 className="text-2xl font-bold">Choose your supply route</h2><p className="mt-3 max-w-2xl text-sm text-white/80">A drawing, a section list or a window schedule helps us scope the next step. Early technical and sample inquiries are welcome.</p><div className="mt-6 flex flex-wrap gap-3"><Link href={buildWindowRfqHref({ mode: "profiles", source: "window-hub", productPath: pagePath })} className="rounded-lg bg-white px-5 py-3 text-sm font-bold text-deep">Request a Profile Quote →</Link><Link href={buildWindowRfqHref({ mode: "finished", source: "window-hub", productPath: pagePath })} className="rounded-lg border border-white/40 px-5 py-3 text-sm font-bold text-white">Request a Finished-Unit Quote →</Link></div></div></div></section>
  </>;
}
