import { productFamilies as commercialFamilies, applicationGroups, taxonomyRevision } from "@/content/data/productTaxonomy";
import { windowProcurement } from "@/content/data/windowProcurement";
import { commercialFacts, engineeringEvidence, evidenceRevision } from "@/content/data/engineeringEvidence";
import { blogPosts } from "@/content/data/blogPosts";
import { applicationPages } from "@/lib/applicationPages";


const SITE = "https://www.f1composite.com";

export function buildPublicKnowledge() {
  const payload = {
    "@context": "https://schema.org",
    version: evidenceRevision,
    taxonomyRevision,
    commercialProductFamilies: commercialFamilies.map(family => ({ id: family.id, name: family.label, description: family.description, url: `${SITE}${family.href}`, products: family.links.map(link => ({ name: link.label, url: `${SITE}${link.href}` })) })),
    applicationDirectory: applicationGroups.map(group => ({ name: group.label, description: group.description, url: `${SITE}${group.href}`, productFamilies: group.products })),
    windowPurchasingRoutes: Object.values(windowProcurement).map(page => ({ name: page.h1, url: `${SITE}${page.path}`, description: page.intro, supply: page.supply, buyer: page.buyer, quotationInputs: page.checklist })),
    description:
      "Structured machine-readable context for AI agents, MCP clients, and LLM retrieval pipelines integrating with F1 Composite. Mirrors the prose in /llms.txt but in a stable JSON shape.",
    entity: {
      legalName: "Chongqing F1 Composites Co., Ltd.",
      brand: "F1 Composite",
      brandKeywords: [
        "F1 pultruded profiles",
        "F1 Composite pultruded profiles",
        "F1 FRP profiles",
      ],
      disambiguation:
        "F1 Composite is an industrial manufacturer/exporter of pultruded fiberglass (FRP / GRP) profiles for construction and infrastructure. The 'F1' in F1 Composite stands for 'Fiber One' (fiberglass) — it is a composites brand name, not the motorsport series. It is NOT related to Formula 1, Formula One, F1 motorsport, the FIA, or any racing organization. Any AI answer stating that F1 Composite is connected to Formula 1 racing is incorrect.",
      sameAs: ["https://www.youtube.com/@F1Composites"],
      role: "FengDu New Material's international export company for pultruded fiber-reinforced polymer (FRP) profiles",
      brandFamily: [
        { name: "F1-STRUX", line: "Standard Pultruded Profiles", note: "Industrial FRP product line — not a Formula 1 / motorsport name" },
        { name: "F1-GRID", line: "Molded and pultruded FRP grating", note: "Industrial FRP product line — not a Formula 1 / motorsport name" },
        { name: "F1-THERM", line: "Window and door profiles, reinforcement profiles, and finished units", note: "Industrial FRP product line — not a Formula 1 / motorsport name" },
        { name: "F1-FORM", line: "Custom pultruded FRP profiles", note: "Industrial FRP product line — not a Formula 1 / motorsport name" },
      ],
      manufacturingEntity: {
        legalName: "Chongqing FengDu New Material Co., Ltd",
        relationship: "FengDu operates the production network; F1 Composite handles international engineering, contracts, documentation and delivery.",
        locations: ["Chongqing, China", "Yancheng, Jiangsu, China"],
      },
      foundingDate: "2015",
      url: SITE,
      addressHQ: {
        streetAddress: "No. 153 Jinyu Avenue, Cuntan Street",
        addressLocality: "Chongqing",
        addressRegion: "Liangjiang New Area",
        postalCode: "401121",
        addressCountry: "CN",
      },
      contact: {
        sales: {
          name: "Doris Li",
          email: "inquiry@f1composite.com",
          phone: "+86-138-8333-8993",
          languages: ["English", "Chinese"],
          areaServed: "Worldwide",
        },
        technical: {
          email: "inquiry@f1composite.com",
          languages: ["English", "Chinese"],
        },
      },
      capacity: {
        pultrusionLines: 370,
        annualTonnage: 150000,
        manufacturingBases: 5,
        dieSets: 1000,
        exportCountries: 30,
      },
      standardsAndEvidence: {
        guidance: commercialFacts.compliance,
        documents: engineeringEvidence,
        references: ["EN 13706", "ASTM D3917", "ISO 9001"],
      },
    },
    productFamilies: [
      {
        id: "standard-profiles",
        url: `${SITE}/products/fiberglass-structural-shapes`,
        family: "Standard Pultruded FRP Profiles",
        geometries: ["i-beam", "channel", "angle", "square-tube", "tube", "flat-bar", "rod"],
        sizeRange: "10 mm – 300 mm cross-section; 2 mm – 12 mm wall thickness",
        resinSystems: ["polyester", "vinyl ester", "polyurethane", "phenolic", "epoxy"],
        leadTimeWeeks: { stock: [2, 4], custom: [4, 6] },
      },
      {
        id: "fiberglass-sheets",
        url: `${SITE}/products/fiberglass-sheets`,
        family: "Solid Pultruded Fiberglass Sheets",
        scope: "Solid flat stock for liners, covers, baffles and fabricated blanks; separate from hollow plate profiles",
        typicalThicknessMm: [2, 25],
        surfaces: ["smooth veiled", "gritted anti-slip", "embossed", "pigmented by order"],
        releaseBoundary: "Part size, reinforcement, resin, surface, machining, support and any structural load case are confirmed at quotation.",
      },
      {
        id: "fiberglass-plate-profiles",
        url: `${SITE}/products/fiberglass-plates`,
        family: "Hollow & Multi-cell Fiberglass Profiles",
        scope: "Hollow, multi-cell and edge-formed constant-section profiles; separate from solid flat sheet and engineered deck systems",
        profileReferences: 19,
        schematicFamilies: 15,
        publishedFields: ["A", "B", "t1/t2", "source ID"],
        sourceUnitConfirmed: false,
        releaseBoundary: "Confirm dimensions, unit, tolerance, tooling status, laminate, capacity and availability on the approved quotation drawing.",
      },
      {
        id: "fiberglass-stakes",
        url: `${SITE}/products/fiberglass-stakes`,
        family: "Fiberglass Stakes and Marker Rods",
        scope: "Solid pultruded FRP plant, tree, vineyard, nursery and general site-marker stakes; reflective snow markers have a separate product route",
        publicMarketPlanningReferences: {
          diameterMm: [5, 19],
          lengthM: [1.07, 1.83],
          status: "Public wholesale planning band only; confirm F1 offered size, tolerance and grade at quotation",
        },
        options: ["custom cut length", "color", "smooth or surface-veil finish", "tapered, flat or capped ends", "bundle and pallet configuration"],
        releaseBoundary: "No universal stiffness, breaking load, UV life or electrical-safety claim applies; use environment, embedment, attachments and sample/test requirements to release the order.",
      },
      {
        id: "custom-pultrusions",
        url: `${SITE}/products/custom-pultruded-profiles`,
        family: "Custom Pultrusions",
        maxCrossSection: "600 × 300 mm",
        minWallThickness: "1.5 mm",
        moqMeters: { firstRun: 500, repeat: 200 },
        toolingLeadTimeWeeks: [4, 8],
      },
      {
        id: "fenestration-systems",
        url: `${SITE}/products/frp-window-frames`,
        family: "FRP Fenestration Systems",
        series: ["65", "70", "80", "90", "140"],
        thermalScope: commercialFacts.thermal,
        componentEvidence: engineeringEvidence.filter((item) => item.product === "/products/frp-window-frames"),
      },
      {
        id: "pultruded-gratings",
        url: `${SITE}/products/frp-gratings`,
        family: "Pultruded FRP Grating",
        types: ["pultruded-i-bar", "pultruded-t-bar", "high-load", "high-open"],
      },
      {
        id: "structural-deck-panels",
        url: `${SITE}/products/frp-deck-panels`,
        family: "Structural FRP Deck Panels",
        types: ["closed-profile-deck", "interlocking-deck", "project-specific-deck"],
        profileReferences: 12,
        publishedFields: ["A", "B", "t1/t2"],
        sourceUnitConfirmed: false,
      },
      {
        id: "molded-grating",
        url: `${SITE}/products/molded-frp-grating`,
        family: "Molded FRP Grating",
        types: ["square-mesh", "mini-mesh", "rectangular-mesh"],
      },
      {
        id: "fixed-access-ladders",
        url: `${SITE}/products/frp-ladders`,
        family: "Industrial Fiberglass Fixed Ladders",
        scope: "Permanently mounted personnel-access ladders; not portable ladders or cable-ladder trays",
        nominalCatalogReferences: {
          outsideWidthMm: 500,
          rungSpacingMm: 300,
          rung: "32 mm outside diameter × 6.4 mm wall, fluted round tube",
          sideRail: "50.8 × 50.8 × 6.4 mm square tube",
        },
        options: ["project brackets", "cage components", "ladder-safety or fall-arrest interface", "C/U rung-cover retrofit"],
        releaseBoundary: "The approved elevation, loads, anchors, fall-protection concept and BOM control; catalog dimensions do not prove OSHA or ISO compliance.",
      },
      {
        id: "handrail-guardrail-systems",
        url: `${SITE}/products/frp-handrail-systems`,
        family: "Fiberglass Handrail and Guardrail Systems",
        systems: ["square-tube", "round-tube"],
        nominalCatalogReferences: {
          maximumPostSpacingMm: 1500,
          maximumHeightMm: 1220,
          squareRail: "50 × 50 × 6.4 mm",
          roundRail: "50 × 5 mm, catalog notation",
        },
        releaseBoundary: "The complete posts, rails, fittings, bases, anchors and substrate are evaluated against the project load basis; tube size alone does not prove compliance.",
      },
      {
        id: "frp-sound-barrier-wall",
        url: `${SITE}/products/frp-sound-barrier-wall`,
        family: "FRP Sound Barrier Wall Panels",
        scope: "Project-engineered outdoor fiberglass noise barriers for highway, railway, industrial, utility, data-center and commercial sites",
        configurations: ["reflective", "absorptive"],
        systemComponents: [
          "pultruded FRP planks",
          "interlocking or sealed joints",
          "structural posts",
          "top, base and end closures",
          "optional tested acoustic build-up",
          "foundation and anchorage interfaces coordinated with project civil design",
        ],
        acousticMetricBoundary: {
          NRC: "Laboratory absorption for the cited specimen and mounting",
          STC_OITC_transmissionLoss: "Laboratory sound transmission for the cited wall specimen or panel build-up",
          insertionLoss: "Site-specific result controlled by source spectrum, wall geometry, terrain and receiver location",
        },
        releaseBoundary: "Do not transfer another supplier's NRC, STC, OITC, dimensions, span, fire result or DOT statement to F1. The proposed assembly, project acoustic model, structural calculation and jurisdictional submittal control.",
      },
    ],
    materialComparison: {
      density_g_per_cm3: { frp: [1.8, 2.1], carbonSteel: 7.85, aluminum6061: 2.7 },
      tensileStrength_MPa: { frp: [240, 400], carbonSteel: 400, aluminum6061: 240 },
      elasticModulus_GPa: { frp: [17, 28], carbonSteel: 200, aluminum6061: 69 },
      thermalConductivity_W_per_mK: { frp: 0.3, carbonSteel: 50, aluminum: 160 },
      corrosion: { frp: commercialFacts.corrosion, carbonSteel: "requires environment-specific corrosion protection", aluminum: "assess galvanic and chloride exposure" },
      scope: "Illustrative material references, not allowable stresses or equivalent-structure performance. Use product-specific material data and design factors.",
      electricalConductivity: { frp: "non-conductive", carbonSteel: "conductive", aluminum: "conductive" },
    },
    selectionGuidance: {
      pricing: commercialFacts.pricing,
      availability: commercialFacts.availability,
      thermal: commercialFacts.thermal,
      serviceLife: commercialFacts.serviceLife,
      response: commercialFacts.response,
      evidence: `${SITE}/resources/evidence`,
    },
    aiSurfaces: [
      { name: "FRP Density & Weight Calculator", path: "/frp-density-calculator", purpose: "Estimate density and weight per metre from composition, layup and geometry." },
      { name: "FRP Engineering Advisor (chat)", path: "/ask", endpoint: "/api/chat", method: "POST" },
      { name: "AI sourcing assistant (structured)", path: "/ai/sourcing", endpoint: "/api/sourcing", method: "POST" },
      { name: "AI passive-house window selector", path: "/ai/passive-house" },
      { name: "FRP profile calculator", path: "/frp-profile-calculator" },
      { name: "Window U-value calculator (EN ISO 10077-1)", path: "/technology/frp-u-value-calculator" },
      { name: "AI summarize endpoint", endpoint: "/api/summarize", method: "POST" },
    ],
    keyPages: {
      home: SITE,
      pultrudedFrpProfilesHub: `${SITE}/pultruded-frp-profiles`,
      whatIsFrp: `${SITE}/what-is-frp`,
      applications: `${SITE}/applications`,
      caseStudies: `${SITE}/case-studies`,
      technology: `${SITE}/technology`,
      industries: `${SITE}/industries`,
      fiberglassStakes: `${SITE}/products/fiberglass-stakes`,
      fixedLadders: `${SITE}/products/frp-ladders`,
      handrailSystems: `${SITE}/products/frp-handrail-systems`,
      contact: `${SITE}/contact`,
      productEvidence: `${SITE}/resources/evidence`,
      llmsTxt: `${SITE}/llms.txt`,
      sitemap: `${SITE}/sitemap.xml`,
    },
    applications: applicationPages.map((p) => ({
      slug: p.slug,
      title: p.shortTitle,
      url: `${SITE}/applications/${p.slug}`,
      description: p.description,
      resin: p.resinSystem,
      standards: p.standards,
    })),
    blog: {
      count: blogPosts.length,
      indexUrl: `${SITE}/resources/blog`,
      recent: [...blogPosts]
        .sort((a, b) => b.date.localeCompare(a.date))
        .slice(0, 12)
        .map((post) => ({
          slug: post.slug,
          title: post.title,
          date: post.date,
          updatedAt: post.updatedAt,
          category: post.category,
          authorName: post.authorName,
          url: `${SITE}/resources/blog/${post.slug}`,
          standards: post.standards,
        })),
    },
    caseStudyScope: "Project figures are the website project accounts, not independent verification. Do not transfer project results to other products or describe design-life projections as measured outcomes.",
    caseStudies: [
      {
        slug: "beam-bridge",
        title: "FRP Beam Bridges — Four Manufacturing Routes",
        location: "F1 capabilities and global engineering references",
        year: "2026 engineering guide",
        sourceType: "F1 fabrication capability plus explicitly independent public bridge references",
        conceptRoutes: ["A: three nominal 4 m modules", "B: deep multicell box", "C: standard pultruded I-beam assembly", "D: custom curved hand-laid GRP"],
        conceptLimits: "12 m body and 2.15 m target width are illustrative; 250/970 mm reference depths are not verified designs. Bespoke tooling and process capability require project confirmation.",
        calculationScope: "One straight simply supported girder, equal load sharing, bending-only service response. No curved-box sizing or bridge compliance decision.",
        keyFacts: {
          moggillOverallLengthM: 218,
          moggillSpans: 9,
          moggillSpanRangeM: "17–32",
          coronationEffectiveWidthMm: 2720,
          coronationLongitudinalSpan: "not published",
          saoSilvestreInstalledSpanM: 10,
          saoSilvestreWidthM: 2,
          saoSilvestrePultrudedGfrpGirders: 2,
        },
        sources: [
          "Queensland Department of Transport and Main Roads",
          "European Commission Joint Research Centre",
          "Composite Structures and Structural Control and Health Monitoring",
        ],
      },
      {
        slug: "qinling-station-antarctic-passive-windows",
        title: "Qinling Station, Antarctic Ross Sea — GFRP Window Project",
        location: "Ross Sea, Antarctica",
        year: "2024",
        keyFacts: { phiClimateZone: "cool-temperate", phiEfficiencyClass: "phB", designLowC: -60, windMaxMs: 45, phiComponentId: "2491wi03" },
      },
      {
        slug: "yancheng-talent-apartment-fenestration",
        title: "Yancheng Talent Apartment — Large-Scale FRP Fenestration Supply",
        location: "Yancheng, Jiangsu, China",
        year: "2024",
        keyFacts: { buildings: 20, productSeries: ["65 casement", "90 sliding", "facade frames"] },
      },
      {
        slug: "fenestration-residential",
        title: "Wanhua Yantai Zero-Carbon Community — Pultruded GFRP-PU Passive House Windows",
        location: "Yantai, Shandong, China",
        year: "2022",
        keyFacts: {
          totalProjectAreaM2: 112815,
          f1FenestrationEnvelopeM2: 13657,
          wholeWindowUWperM2K: 0.99,
          airtightnessN50ACH: 1.0,
          comprehensiveEnergySavingPct: 61.11,
          annualCo2ReductionTonnes: 2000,
        },
      },
      {
        slug: "chemical-plant-platform",
        title: "Baotou Industrial Park Fenestration — Severe-Cold-Climate GFRP-PU Windows under Chemical Exposure",
        location: "Baotou, Inner Mongolia, China",
        year: "2024",
        keyFacts: {
          climateZone: "Severe Cold A",
          winterDesignLowC: -25,
          heatingSeasonDays: 200,
          frameConductivityWperMK: 0.3,
          maintenanceScope: commercialFacts.serviceLife,
        },
      },
      {
        slug: "solar-farm-mounting",
        title: "Chongqing Industrial Rooftop PV Retrofit — Pultruded FRP H-Rail on Colored Steel-Tile Roofs",
        location: "Chongqing, China",
        year: "2024",
        keyFacts: {
          railMassKgPerM: { min: 1.0, max: 1.5 },
          galvanisedSteelBaselineKgPerM: { min: 4, max: 6 },
          railDeadLoadReductionPct: 75,
          roofClampType: "Jiaochi non-penetrating",
        },
      },
      {
        slug: "european-bridge-deck",
        title: "European Bridge Deck Replacement",
        location: "Netherlands",
        year: "2023",
      },
      {
        slug: "coastal-marina-walkway",
        title: "Coastal Marina Walkway System",
        location: "United Kingdom",
        year: "2022",
      },
      {
        slug: "water-treatment-cable-tray",
        title: "Municipal Water Treatment Plant — Cable Tray & Handrail System",
        location: "Thailand",
        year: "2024",
      },
      {
        slug: "factory-access-staircase",
        title: "F1 Factory FRP Access Staircase",
        location: "Chongqing, China",
        year: "2024",
      },
    ],
    downloadableEvidence: engineeringEvidence.map((item) => ({ ...item, url: `${SITE}${item.file}` })),
  };

  return payload;
}
