// Generated by scripts/build-pultrusion-guide-index.mjs; do not edit.
import type { ApplicationPage } from "@/lib/applicationPages";

export const specialistApplicationPages: ApplicationPage[] = [
  {
    "slug": "frp-wastewater-clarifier-components",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "FRP Clarifier Components | Sludge Flights, Weirs & Baffles",
    "shortTitle": "Wastewater clarifier components",
    "description": "Specify pultruded FRP clarifier flights, weirs, scum baffles and supports, with guidance on mechanical interfaces, materials and acceptance standards.",
    "h1": "Pultruded FRP components inside wastewater clarifiers",
    "intro": "A clarifier has several different jobs: settle solids, collect sludge, retain surface scum and discharge clarified water. Select the composite component around its particular job and the existing equipment interfaces.",
    "environment": "F1 can assess drawings for pultruded flights, flat profiles and support sections, with agreed cutting and drilling. Hydraulic design, collector drives, chains, controls, installation and complete treatment performance require separately assigned responsibilities and qualification.",
    "supplyScope": "F1 can assess drawings for pultruded flights, flat profiles and support sections, with agreed cutting and drilling. Hydraulic design, collector drives, chains, controls, installation and complete treatment performance require separately assigned responsibilities and qualification.",
    "image": "/images/applications/guides/frp-wastewater-clarifier-components.svg",
    "imageAlt": "Longitudinal clarifier section with separate flights on upper and lower chain runs, a sludge hopper, scum trough, fixed baffle and overflow weir.",
    "imageNote": "Application schematic",
    "imageCaption": "Upper flights move scum toward collection; lower flights move sludge toward the hopper. Water passes below the fixed baffle and over the weir. Inlet and drive layout are outside this component section.",
    "recommendedProfiles": [
      "Custom constant-section collector flights",
      "Flat profiles machined as weirs or scum baffles",
      "Angles, channels and tubes for mounting supports",
      "Agreed filler blocks and connection components"
    ],
    "resinSystem": "Review a specified glass-fiber thermoset laminate against the actual liquid, solids, cleaning chemicals, temperature and contact duration. Resin family names alone do not establish compatibility.",
    "standards": [
      "ASTM D3917-23",
      "ASTM D543-21",
      "AWWA F101-25 / F102-25",
      "OSHA 29 CFR 1910.147 and 1910.146",
      "NSF/ANSI/CAN 61"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Plant location, owner requirements, process stage and municipal or industrial wastewater duty",
      "Basin plan and section, as-built survey, normal and exceptional water levels",
      "Collector manufacturer/model, chain spacing, travel direction, attachment and wear-shoe drawings",
      "Operating loads and protection settings established by the equipment designer",
      "Normal and upset chemistry, solids/grit, liquid and cleaning temperatures, contact duration",
      "Profile geometry, laminate properties required for design, drilling datum and critical tolerances",
      "Weir crest and baffle geometry, support spacing, anchors, joints and acceptance survey requirements",
      "Quantity and cut lengths, trial quantities, spares and identification requirements",
      "Manufacturing process of each part, invoked standards and any accepted alternatives",
      "Inspection/test plan, trial-fit and commissioning responsibilities, shutdown window and delivery sequence"
    ],
    "related": [
      {
        "href": "/products/frp-sludge-collector-flights",
        "label": "Sludge collector flight specifications"
      },
      {
        "href": "/industries/water-wastewater",
        "label": "Water and wastewater industry"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profiles"
      },
      {
        "href": "/products/fiberglass-structural-shapes",
        "label": "Structural support sections"
      }
    ]
  },
  {
    "slug": "frp-pulp-paper-mill-components",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "FRP for Pulp & Paper Mills | Access & Support Specification",
    "shortTitle": "Pulp and paper mill components",
    "description": "Plan pultruded FRP access and supports for pulp and paper mills. Review chemical exposure, connections, shutdown work, maintenance and workplace rules.",
    "h1": "Pultruded FRP access and support components for pulp and paper mills",
    "intro": "A paper mill contains wet stock preparation, chemical handling, bleaching and hot equipment zones. Map the actual duty before specifying a walkway, support frame or replacement component.",
    "environment": "F1 can assess pultruded beams, channels, tubes, angles and grating components for an agreed access or support package. Process vessels, pressure equipment, paper-machine internals, machinery certification and plant installation require separate specialist scopes.",
    "supplyScope": "F1 can assess pultruded beams, channels, tubes, angles and grating components for an agreed access or support package. Process vessels, pressure equipment, paper-machine internals, machinery certification and plant installation require separate specialist scopes.",
    "image": "/images/applications/guides/frp-pulp-paper-mill-components.svg",
    "imageAlt": "Braced FRP access platform with anchored footings beside independently supported process equipment.",
    "imageNote": "Application schematic",
    "imageCaption": "Follow platform loads through the grating, beams, braced columns and anchored bases. The vessel has its own supports, and the pipework clears the access platform.",
    "recommendedProfiles": [
      "I-beams and channels for access framing",
      "Tubes and angles for bracing and guardrail components",
      "Pultruded grating and stair components",
      "Custom support or mounting profiles under an approved drawing"
    ],
    "resinSystem": "Select a documented glass-fiber laminate for the identified chemical exposure, temperature, cleaning regime, mechanical duty and fire requirements. Assess metal connections and repaired or cut surfaces within the same exposure review.",
    "standards": [
      "OSHA 29 CFR 1910.261",
      "OSHA 29 CFR 1910.22 and 1910.29",
      "OSHA 29 CFR 1910.147 and 1910.146",
      "ASTM D543-21",
      "ASTM D7290-06(2022)"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Mill location, process area and applicable owner, building and workplace requirements",
      "Operator tasks, equipment removal routes, emergency access and shutdown constraints",
      "Controlled plan and sections, support survey, pipe penetrations and retained-structure condition",
      "Permanent, access, maintenance and equipment loads identified by the responsible designer",
      "Chemical names/concentrations, normal and abnormal temperatures, mist/splash/immersion and cleaning schedule",
      "Required laminate evidence, fire criteria where applicable and conditions needing separate qualification",
      "Member and grating layout, bearing direction, cutouts, panel restraint and removable-section plan",
      "Guardrails, stairs, openings and connection interfaces with assigned design responsibility",
      "Cutting/drilling drawings, identification, edge treatment, hardware and anchor supply scope",
      "Trial assembly, inspection records, as-built handover, spares and delivery sequence"
    ],
    "related": [
      {
        "href": "/industries/industrial",
        "label": "Industrial and chemical applications"
      },
      {
        "href": "/applications/frp-chemical-plant-platforms",
        "label": "Chemical plant platform planning"
      },
      {
        "href": "/products/frp-gratings",
        "label": "Pultruded grating"
      },
      {
        "href": "/products/frp-handrail-systems",
        "label": "Industrial handrail systems"
      },
      {
        "href": "/products/fiberglass-structural-shapes",
        "label": "Structural profiles"
      }
    ]
  },
  {
    "slug": "frp-transformer-insulation-supports",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "FRP Transformer Insulation Supports | Design & Qualification",
    "shortTitle": "Dry-type transformer insulation supports",
    "description": "Specify pultruded fiberglass winding spacers and supports for dry-type transformers: thermal classes, contact loads, cooling, insulation and RFQ evidence.",
    "h1": "FRP insulation supports for dry-type transformers",
    "intro": "A winding support must maintain position, carry its assigned loads and preserve the cooling and insulation arrangement. Define those jobs together before selecting a dog-bone, channel, angle or custom pultruded section.",
    "environment": "Send a component drawing and equipment qualification requirements for feasibility review. This guide concerns pultruded support components; it does not establish an F1 thermal class, transformer approval or validated insulation system.",
    "supplyScope": "Send a component drawing and equipment qualification requirements for feasibility review. This guide concerns pultruded support components; it does not establish an F1 thermal class, transformer approval or validated insulation system.",
    "image": "/images/applications/guides/frp-transformer-insulation-supports.svg",
    "imageAlt": "Transverse winding section with a dogbone composite spacer and axial cooling ducts indicated out of the page.",
    "imageNote": "Application schematic",
    "imageCaption": "The dogbone spacer separates adjacent winding sections. Its length and the cooling flow run out of the page; circle-dot symbols identify the axial ducts.",
    "recommendedProfiles": [
      "Dog-bone winding spacers",
      "Insulating channels and angles",
      "Support strips and custom constant-section holders"
    ],
    "resinSystem": "Glass-reinforced thermoset profiles with a project-qualified resin, reinforcement and surface system",
    "standards": [
      "IEC 60076-11:2018",
      "IEC 60085:2007",
      "IEC 60076-5:2006"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Transformer type, equipment standard and edition, rated capacity, operating voltages and intended installation country.",
      "Annotated winding/core/clamp arrangement, part function, fiber direction, support drawing and functional datums.",
      "Local continuous and peak temperatures, duty duration, thermal cycles, cooling passages and the insulation-system class required by the OEM.",
      "Assembly preload, sustained and transient loads, short-circuit reactions, transport loads and allowable deformation.",
      "Air-clearance and creepage requirements, altitude, contamination, moisture and the proposed equipment dielectric tests.",
      "Profile dimensions, length, straightness, twist, contact faces, machining, edge treatment and cleanliness requirements.",
      "Qualification and batch-acceptance plan, material-change control, traceability, first-article quantities and series forecast."
    ],
    "related": [
      {
        "href": "/products/fiberglass-dog-bone",
        "label": "Fiberglass dog-bone profile geometry"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profile development"
      },
      {
        "href": "/industries/energy",
        "label": "Energy and electrical applications"
      }
    ]
  },
  {
    "slug": "frp-third-rail-protection",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "FRP Third-Rail Protection | Coverboard Design Guide",
    "shortTitle": "Third-rail protection systems",
    "description": "Plan pultruded third-rail coverboards around collector clearance, brackets, weather, fire requirements, electrical protection and operator qualification.",
    "h1": "FRP third-rail protection from profile to track assembly",
    "intro": "A third-rail cover is part of an operator-defined protection arrangement. Its cross-section, supports, ends and joints must fit the conductor and collector envelope while retaining the required mechanical and electrical performance in service.",
    "environment": "F1 can review a drawing-led coverboard component inquiry and the evidence required for qualification. No standard stock cover, approved railway system or safe-access condition is asserted by this guide.",
    "supplyScope": "F1 can review a drawing-led coverboard component inquiry and the evidence required for qualification. No standard stock cover, approved railway system or safe-access condition is asserted by this guide.",
    "image": "/images/applications/guides/frp-third-rail-protection.svg",
    "imageAlt": "Side-contact conductor rail on an insulating support beneath an FRP cover, with a separate cover bracket and collector shoe envelope.",
    "imageNote": "Application schematic",
    "imageCaption": "Side-contact example: the shoe meets the rail beside its insulating support. The cover bracket is a separate component, and the dashed outline marks collector travel.",
    "recommendedProfiles": [
      "Custom open cover sections",
      "Returned-edge coverboards",
      "Profile-based joint and end components subject to separate review"
    ],
    "resinSystem": "Project-qualified glass-reinforced thermoset profiles, with fire and electrical requirements defined for the installation",
    "standards": [
      "EN 50122-1:2022+A1:2025",
      "NFPA 130, 2026 edition",
      "EN 45545-2:2020+A1:2023"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Operating authority, country, project approval route and exact adopted standards and editions.",
      "System operating and maximum voltages, rail cross-section, contact arrangement and collector dynamic envelope.",
      "Cover and bracket CAD, installed tolerances, support spacing, joints, end transitions and removable sections.",
      "Wind, snow, ice, impact and any defined maintenance load, with allowable deflection and connection reactions.",
      "Component temperature range, tunnel or outdoor exposure, contamination, water, cleaning media and drainage arrangement.",
      "Electrical, fire and smoke test matrix, conditioning, accepted thicknesses and surface finishes, and approving parties.",
      "First-article trial location, quantities and cut lengths, installation constraints, identification and batch inspection documents."
    ],
    "related": [
      {
        "href": "/products/frp-third-rail-coverboards",
        "label": "Specify a third-rail coverboard profile"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom section development"
      },
      {
        "href": "/industries/infrastructure",
        "label": "FRP in transport infrastructure"
      }
    ]
  },
  {
    "slug": "frp-live-line-tool-components",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "FRP Live-Line Tool Components | Qualification Guide",
    "shortTitle": "Live-line tool component qualification",
    "description": "Develop a specification for fiberglass live-line tool rods and foam-filled tubes, separating component tests, complete-tool qualification and employer duties.",
    "h1": "Qualifying FRP components for live-line tools",
    "intro": "A fiberglass rod or tube becomes a candidate tool component only through a defined material, fabrication and qualification process. Establish the applicable component standard and complete-tool acceptance route before selecting a profile.",
    "environment": "This is a component feasibility and qualification inquiry. F1 has not established a dedicated live-line tool qualification through this page. It is not an offer of an approved complete tool, a working-voltage rating or instructions for energized work.",
    "supplyScope": "This is a component feasibility and qualification inquiry. F1 has not established a dedicated live-line tool qualification through this page. It is not an offer of an approved complete tool, a working-voltage rating or instructions for energized work.",
    "image": "/images/applications/guides/frp-live-line-tool-components.svg",
    "imageAlt": "Insulating component between metal fittings, with an exposed-section dimension and separate solid-rod and foam-filled-tube cross-sections.",
    "imageNote": "Application schematic",
    "imageCaption": "The dimension spans exposed insulation between fitting edges. The two sections distinguish a solid rod from an FRP wall around foam; this is not a working-distance specification.",
    "recommendedProfiles": [
      "Solid insulating rods",
      "Circular foam-filled insulating tubes",
      "Drawing-controlled component ends subject to tool-maker qualification"
    ],
    "resinSystem": "Candidate fiberglass-reinforced insulating solid rod or foam-filled tube, subject to application-specific qualification",
    "standards": [
      "ASTM F711-26",
      "IEC 60855-1:2016",
      "29 CFR 1910.269(j)"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Requested deliverable: blank profile, fabricated insulating component, fitted component or complete tool, with each party's qualification responsibilities.",
      "Intended tool function, destination country, applicable standards and exact editions, and the tool manufacturer's acceptance procedure.",
      "Solid or foam-filled construction, circular-section dimensions where applicable, length, straightness, mass and functional surface requirements.",
      "Tool-head and connection drawings, mechanical load cases, stiffness targets, fabrication and assembly process requirements.",
      "Temperature, moisture and contamination exposure, approved cleaning system, marking and protective packaging.",
      "Design, routine and acceptance test plan, conditioning, test responsibility, required reports and change-control procedure.",
      "First-article quantities, production forecast, traceability and explicit identification of development parts not released for field use."
    ],
    "related": [
      {
        "href": "/products/fiberglass-live-line-tool-tubes-rods",
        "label": "Specify insulating rod and tube components"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultrusion feasibility"
      },
      {
        "href": "/industries/energy",
        "label": "Electrical component applications"
      }
    ]
  },
  {
    "slug": "cfrp-concrete-strengthening",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "CFRP Concrete Strengthening | Pultruded Strip Guide",
    "shortTitle": "CFRP concrete strengthening",
    "description": "Specify pultruded CFRP strips for concrete strengthening: existing-structure assessment, bonding, installation controls, inspection and system qualification.",
    "h1": "Pultruded CFRP strips for strengthening concrete",
    "intro": "A carbon strip becomes structural reinforcement only when its load can enter and leave the existing concrete safely. Start with the condition and required capacity of the structure, then specify the strip, adhesive, substrate preparation and acceptance process together.",
    "environment": "F1 can review a component qualification inquiry for pultruded reinforcement against a supplied specification. An accepted strengthening kit, structural design, adhesive selection and site installation require identified specialist responsibilities and project evidence.",
    "supplyScope": "F1 can review a component qualification inquiry for pultruded reinforcement against a supplied specification. An accepted strengthening kit, structural design, adhesive selection and site installation require identified specialist responsibilities and project evidence.",
    "image": "/images/applications/guides/cfrp-concrete-strengthening.svg",
    "imageAlt": "Simply supported concrete beam with downward loading, an adhesive layer, a soffit CFRP strip and marked end-transfer regions.",
    "imageNote": "Application schematic",
    "imageCaption": "For this positive-bending case, the CFRP strip sits on the beam's tension face. The adhesive transfers load into the strip, with transfer regions marked at both ends.",
    "recommendedProfiles": [
      "Flat CFRP strips for externally bonded reinforcement",
      "Narrow strips considered for near-surface-mounted reinforcement",
      "Project-specific cut lengths and prepared bonding faces"
    ],
    "resinSystem": "Project-qualified carbon-fibre laminate, typically with an epoxy matrix; compatible adhesive and substrate repair system selected as an assembly.",
    "standards": [
      "ACI PRC-440.2-23",
      "ACI CODE-440.13-24",
      "EAD 160086-01-0301"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Project country, authority, design basis and responsible structural engineer.",
      "Existing-member drawings, reinforcement survey, condition assessment and current versus required loads.",
      "Externally bonded or near-surface-mounted arrangement; strip orientation, lengths, terminations and interfaces.",
      "Specified laminate stiffness, tensile properties, dimensional tolerances and required test or characteristic-value basis.",
      "Approved adhesive, repair materials, primer or surface treatment, and required evidence for their combination.",
      "Installation access, substrate condition, environmental limits, support requirements and loading restrictions.",
      "Service exposure, protective finish, fire design approach, inspection access and foreseeable alterations.",
      "Sample plan, material traceability, installation inspection, acceptance authority, quantities and delivery schedule."
    ],
    "related": [
      {
        "href": "/products/pultruded-cfrp-strengthening-strips",
        "label": "CFRP strip procurement and qualification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profile inquiries"
      },
      {
        "href": "/industries/infrastructure",
        "label": "Infrastructure applications"
      }
    ]
  },
  {
    "slug": "carbon-fiber-industrial-rollers",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "Carbon-Fiber Industrial Rollers | Web Handling Guide",
    "shortTitle": "Carbon-fibre industrial rollers",
    "description": "Define carbon roller requirements for film, printing and nonwoven lines: load paths, rotor behaviour, surfaces, end fittings, commissioning and qualification.",
    "h1": "Carbon-fibre components for industrial rollers",
    "intro": "A light tube is only the starting point for a production roller. The working surface, end connections, bearings and rotating assembly must deliver the required web handling, dimensional accuracy and machine behaviour together.",
    "environment": "F1 can review a CFRP component feasibility and qualification inquiry. Precision finishing, end fittings, balancing, bearings and qualification of a finished roller must be separately defined and confirmed; they are not assumed supply capabilities.",
    "supplyScope": "F1 can review a CFRP component feasibility and qualification inquiry. Precision finishing, end fittings, balancing, bearings and qualification of a finished roller must be separately defined and confirmed; they are not assumed supply capabilities.",
    "image": "/images/applications/guides/carbon-fiber-industrial-rollers.svg",
    "imageAlt": "Axial roller section with bonded end plugs, journals and bearing supports, beside an end view of a tangent 90-degree web wrap.",
    "imageNote": "Application schematic",
    "imageCaption": "The axial section connects shell, plugs, journals, bearings and frame. The separate end view shows tangent web entry and exit around a quarter-turn wrap.",
    "recommendedProfiles": [
      "Candidate CFRP roller shells",
      "Longitudinal reinforcement for an engineered hybrid shell",
      "Tube components with agreed machining and surface allowances"
    ],
    "resinSystem": "Application-specific CFRP tube construction, potentially requiring transverse or angled reinforcement as well as longitudinal fibres.",
    "standards": [
      "ISO 21940-11:2016 with Amd 1:2022",
      "ISO 21940-12:2016",
      "ISO 12100:2010",
      "29 CFR 1910.212"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Machine and roller function; original interface drawing, web path and the problem to be solved.",
      "Outside and inside diameters, working face length, bearing span, journals, drive and mounting arrangement.",
      "Web material, width, tension, wrap angle, contact pressure or nip load, and torque where driven.",
      "Continuous and maximum speed, acceleration and deceleration, operating cycles and exceptional loads.",
      "Deflection, run-out, surface profile, roughness, vibration and balance acceptance requirements with measurement conditions.",
      "Process temperature, cleaning temperatures and chemicals, surface coating, static-control or hazardous-area requirements.",
      "Bare shell versus finished assembly; responsibilities for end fittings, adhesives, bearings, machining and balancing.",
      "Prototype quantity, inspection plan, traceability, commissioning owner, service access and permitted repair scope."
    ],
    "related": [
      {
        "href": "/products/carbon-fiber-roller-tubes",
        "label": "Roller-tube procurement and qualification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom component inquiries"
      },
      {
        "href": "/industries/industrial",
        "label": "Industrial applications"
      }
    ]
  },
  {
    "slug": "frp-rail-interior-profiles",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "FRP Rail Interior Profiles | Fire Qualification Guide",
    "shortTitle": "Rail interior and secondary profiles",
    "description": "Plan railway interior and secondary pultruded profiles with a defined component function, EN 45545 fire evidence, connections, traceability and change control.",
    "h1": "Pultruded profiles for rail interiors and secondary components",
    "intro": "A railway profile needs a defined job, an agreed material construction and evidence for its actual installation. Fire behaviour, mechanical retention, surface finish and service access should be specified together before choosing a section.",
    "environment": "F1 can review custom-profile qualification inquiries against an OEM specification. Railway acceptance, requirement sets, hazard levels and test coverage must be confirmed for the offered component; no vehicle approval or HL classification is implied.",
    "supplyScope": "F1 can review custom-profile qualification inquiries against an OEM specification. Railway acceptance, requirement sets, hazard levels and test coverage must be confirmed for the offered component; no vehicle approval or HL classification is implied.",
    "image": "/images/applications/guides/frp-rail-interior-profiles.svg",
    "imageAlt": "Rail interior section with secondary FRP supports attached to the carbody, bracket-mounted equipment and a retained ceiling panel.",
    "imageNote": "Application schematic",
    "imageCaption": "Carbody brackets support the secondary FRP frame. Separate brackets carry equipment, while fasteners retain the ceiling panel; primary vehicle structure is outside the profile scope.",
    "recommendedProfiles": [
      "Interior-panel and ceiling support rails",
      "Secondary cover and service-hatch framing",
      "Cable-protection covers and approved equipment enclosure edges"
    ],
    "resinSystem": "Project-defined glass-fibre laminate and fire-retardant resin, including every surface layer and bonded interface relevant to the component evaluation.",
    "standards": [
      "EN 45545-2:2020+A1:2023",
      "IEC 61373:2026"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Country, vehicle programme, OEM specification versions and the authority accepting the component.",
      "Installed location, part function, neighboring materials, exposed faces and consequences of detachment.",
      "Fire standard edition, component requirement set and hazard level provided by the customer.",
      "Section drawing, wall thickness, length, finish, coating, adhesive and relevant assembly construction.",
      "Mechanical load cases, equipment masses, operating cycles, vibration basis and connection drawings.",
      "Machining, edge treatment, installation sequence, inspection access and replacement requirements.",
      "Representative specimen configuration, qualification tests, first-article acceptance and report traceability.",
      "Prototype and production quantities, batch marking, change-notification rules and delivery milestones."
    ],
    "related": [
      {
        "href": "/products/fire-retardant-rail-profiles",
        "label": "Rail-profile procurement and qualification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom profile development"
      },
      {
        "href": "/industries/vehicle",
        "label": "Vehicle and transportation applications"
      }
    ]
  },
  {
    "slug": "frp-switchgear-insulation-components",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "FRP Switchgear Insulation | Supports & Mechanisms",
    "shortTitle": "Switchgear insulation and mechanism components",
    "description": "Specify pultruded FRP switchgear supports and operating parts: insulation paths, fault loads, cycling, thermal duty, material tests and OEM qualification.",
    "h1": "FRP switchgear components: insulation and movement together",
    "intro": "A switchgear support must retain the position and electrical separation established by the equipment design. A moving insulating link must do so throughout its stroke and operating life. Start with the assembly's required behavior, then specify the profile and its interfaces.",
    "environment": "F1 welcomes drawing-led feasibility and qualification inquiries for pultruded insulating components. This page does not establish an approved electrical grade, a switchgear voltage rating, an arc classification or a complete operating mechanism supplied by F1.",
    "supplyScope": "F1 welcomes drawing-led feasibility and qualification inquiries for pultruded insulating components. This page does not establish an approved electrical grade, a switchgear voltage rating, an arc classification or a complete operating mechanism supplied by F1.",
    "image": "/images/applications/guides/frp-switchgear-insulation-components.svg",
    "imageAlt": "Two switchgear details showing an FRP support between a metal frame and live busbar, and an insulating operating link between a moving contact and drive.",
    "imageNote": "Application schematic",
    "imageCaption": "Separate support and operating-link details: teal identifies composite insulation, ochre identifies conductive parts, and grey identifies the frame and fittings.",
    "recommendedProfiles": [
      "Insulating support angles and channels",
      "Constant-section frame and guide members",
      "Rods or tubes for OEM-qualified insulating linkages"
    ],
    "resinSystem": "Glass-fiber thermoset profiles with resin, reinforcement, surface and fabrication qualified for the equipment",
    "standards": [
      "IEC 61439-1:2020 with the relevant product part",
      "IEC 62271-1:2017+AMD1:2021",
      "IEC 62271-200:2021+AMD1:2024",
      "IEC 60664-1:2020+AMD1:2025",
      "IEC 60112:2025, corrected 2026-02",
      "Regulation (EU) 2024/573: switchgear provisions"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Equipment type, destination market, AC/DC duty, rated voltage and adopted equipment standards with editions.",
      "Component function and annotated assembly drawing showing live parts, grounded parts, travel envelope and datums.",
      "Insulation-coordination requirements, impulse and power-frequency tests, contamination, humidity and altitude.",
      "Normal, fault, switching, transport and installation reactions, operating-cycle target and allowable deformation or play.",
      "Local continuous and temporary temperatures, insulating medium, cleaning agents and fire-performance requirements.",
      "Profile and reinforcement concept, machining, inserts, fasteners, cleanliness, surface finish and packaging.",
      "Material, fabricated-part and equipment qualification responsibilities, change-control rules and batch records.",
      "First-article quantity, fit-check assembly, series forecast, inspection plan and replacement identification requirements."
    ],
    "related": [
      {
        "href": "/products/frp-switchgear-insulating-profiles",
        "label": "Switchgear insulating profile specification"
      },
      {
        "href": "/applications/frp-transformer-insulation-supports",
        "label": "Dry-transformer insulation supports"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profile development"
      },
      {
        "href": "/industries/energy",
        "label": "Energy and electrical applications"
      }
    ]
  },
  {
    "slug": "composite-overhead-conductor-cores",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "Composite Conductor Cores | HTLS Qualification Guide",
    "shortTitle": "Composite cores for overhead conductors",
    "description": "Evaluate composite cores for overhead conductors: material architecture, heat and creep, bending, fittings, sag-tension, installation and qualification.",
    "h1": "Composite overhead conductor cores: from rod to qualified line",
    "intro": "The composite core is one element in a conductor, fitting and line system. Its value depends on retained strength and dimensional behavior through manufacture, installation and operation—not simply the tensile strength of a new straight specimen.",
    "environment": "This guide supports technical feasibility and qualification inquiries only. F1 does not claim a utility-approved conductor core, licensed proprietary conductor system, demonstrated ampacity increase or established maximum service temperature on the basis of this page.",
    "supplyScope": "This guide supports technical feasibility and qualification inquiries only. F1 does not claim a utility-approved conductor core, licensed proprietary conductor system, demonstrated ampacity increase or established maximum service temperature on the basis of this page.",
    "image": "/images/applications/guides/composite-overhead-conductor-cores.svg",
    "imageAlt": "Conductor cross-section showing a central composite tensile core and two segmented aluminum layers.",
    "imageNote": "Application schematic",
    "imageCaption": "The center carries tensile load; the surrounding aluminum provides the current path. Layer geometry and strand count are illustrative and vary with conductor technology.",
    "recommendedProfiles": [
      "Monolithic composite supporting cores",
      "Individual composite wires for a separately designed stranded core",
      "Protected core constructions subject to system qualification"
    ],
    "resinSystem": "Candidate carbon-fiber thermoset cores or other specifically defined polymer-matrix architectures, with qualified protection and interfaces",
    "standards": [
      "ASTM B987/B987M-25",
      "IEC TS 62818-1:2024",
      "IEEE 738-2023",
      "CIGRE TB 426 (2010)",
      "CIGRE TB 763 (2019) and TB 983 (2026)"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Utility, destination country, circuit purpose, existing or new-line status, and responsible conductor/system integrator.",
      "Proposed conductor architecture, core type, dimensional drawing, protective construction and technology-interface requirements.",
      "Continuous, emergency and cyclic temperature duty; required tensile behavior, creep data, environmental exposure and qualification life assumptions.",
      "Conductor geometry, metal strands, sag-tension model inputs, span and structural constraints, and rating-study conditions.",
      "Approved fittings, termination interfaces, manufacturing equipment, reel requirements and installation responsibilities.",
      "Core, conductor and system standards with editions; qualification tests, acceptance limits, witness points and change control.",
      "Development quantities, test-program responsibility, production forecast, traceability and documentation deliverables.",
      "Installation support, inspection method, abnormal-event response and conditions for field repair or replacement approval."
    ],
    "related": [
      {
        "href": "/products/composite-conductor-core-rods",
        "label": "Composite conductor core development inquiry"
      },
      {
        "href": "/applications/frp-switchgear-insulation-components",
        "label": "Switchgear insulating components"
      },
      {
        "href": "/industries/energy",
        "label": "Energy and grid applications"
      }
    ]
  },
  {
    "slug": "cfrp-robotic-beams-struts",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "CFRP Robot Beams & Struts | Engineering Guide",
    "shortTitle": "CFRP robotic beams and struts",
    "description": "Specify carbon-fibre robot beams and struts: stiffness, joints, buckling, fatigue, positioning, machine safety and a staged component qualification plan.",
    "h1": "CFRP beams and struts for industrial robots",
    "intro": "Lower moving mass can help a robot or handling gantry only when the complete member remains stiff, dimensionally stable and securely connected through its operating cycle. Specify the beam, end joints and machine response together.",
    "environment": "F1 can review a component qualification inquiry for a constant-section carbon profile against an OEM specification. Finished robot arms, precision end fittings, bonded assemblies and machine validation require an agreed scope and evidence before any supply commitment.",
    "supplyScope": "F1 can review a component qualification inquiry for a constant-section carbon profile against an OEM specification. Finished robot arms, precision end fittings, bonded assemblies and machine validation require an agreed scope and evidence before any supply commitment.",
    "image": "/images/applications/guides/cfrp-robotic-beams-struts.svg",
    "imageAlt": "Side elevation of a CFRP cantilever beam with a fixed root, bonded sleeve overlaps and a downward tool load.",
    "imageNote": "Application schematic",
    "imageCaption": "One cantilever bending case: follow the load from the tool adapter through the beam and bonded sleeve to the fixed machine root. Torsion and dynamic cases require separate checks.",
    "recommendedProfiles": [
      "Closed rectangular beams for moving gantries",
      "Round or shaped tubes for parallel robot links",
      "Constant-section strut bodies with separately engineered end interfaces"
    ],
    "resinSystem": "Carbon-fibre thermoset profiles with an architecture selected for axial, bending, transverse and torsional loads; any added reinforcement or hybrid manufacture must be specified.",
    "standards": [
      "ISO 12100:2010",
      "ISO 10218-1:2025 and ISO 10218-2:2025",
      "ISO 9283:1998",
      "EU machinery legislation: 2027 transition"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Machine type, intended use, installation country and responsible OEM or integrator.",
      "Payload, moving accessories, load positions, motion history and expected operating life.",
      "Beam span or joint-centre length, cross-section envelope, restraints and interface drawings.",
      "Direction-specific stiffness requirements, deflection limits, buckling and torsional load cases.",
      "Fitting materials, alignment datums, adhesive or mechanical joint scope and inspection access.",
      "Temperature, moisture, cleaning agents, impact exposure and conductive-material constraints.",
      "Component tests, selected machine-performance tests and agreed acceptance authority.",
      "Prototype quantity, expected production volume, traceability and change-notification requirements."
    ],
    "related": [
      {
        "href": "/products/carbon-fiber-robotic-beams",
        "label": "Carbon-fibre beam component specification"
      },
      {
        "href": "/applications/carbon-fiber-industrial-rollers",
        "label": "Carbon-fibre rotating components"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profiles"
      }
    ]
  },
  {
    "slug": "composite-mri-patient-supports",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "Composite MRI Patient Supports | OEM Design Guide",
    "shortTitle": "Composite MRI patient supports",
    "description": "Define composite MRI patient-support requirements: GFRP or CFRP selection, load paths, MR assessment, cleaning, traceability and OEM device qualification.",
    "h1": "Composite profiles for MRI patient-support systems",
    "intro": "A patient support must carry and position a person while preserving the safety and performance of the imaging system. Pultruded profiles can be considered for straight structural elements, but material selection is only one part of the OEM's mechanical, MR and device qualification.",
    "environment": "F1 can review an OEM component qualification inquiry for a profile or machined structural blank. This page does not establish a medical-device supply history, MR classification, biological evaluation, regulatory clearance or medical quality-system certification for F1.",
    "supplyScope": "F1 can review an OEM component qualification inquiry for a profile or machined structural blank. This page does not establish a medical-device supply history, MR classification, biological evaluation, regulatory clearance or medical quality-system certification for F1.",
    "image": "/images/applications/guides/composite-mri-patient-supports.svg",
    "imageAlt": "Longitudinal MRI scanner section showing a patient table entering the open bore with housing clearance and pedestal support.",
    "imageNote": "Application schematic",
    "imageCaption": "Longitudinal section: the patient and sliding top travel along the open bore. The clearance bracket marks the gap below the support; conductive CFRP and connected hardware require OEM MR assessment.",
    "recommendedProfiles": [
      "Straight patient-table longitudinal supports",
      "Profile blanks for equipment support rails",
      "Drawing-specific structural members outside or adjacent to an imaging region"
    ],
    "resinSystem": "Candidate glass-fibre or carbon-fibre thermoset construction selected and evaluated for the actual scanner, component location, load and exposure; no universal MR-safe material designation is assumed.",
    "standards": [
      "FDA MR testing and labeling guidance, October 2023",
      "ASTM F2503-26",
      "IEC 60601-2-33:2022",
      "ISO 14971:2019 and ISO 10993-1:2025",
      "21 CFR Part 820: QMSR",
      "Regulation (EU) 2017/745"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Device or accessory description, intended market, legal manufacturer and component regulatory role.",
      "System drawing, scanner relationship, bore entry, patient proximity and all connected hardware.",
      "Load cases, support conditions, component life, stiffness limits and failure consequences.",
      "Candidate composition, reinforcement architecture, surface treatment and conductive features.",
      "MR assessment owner, intended scanner conditions and mechanical/image-quality acceptance criteria.",
      "Contact scenario, covers, cleaning or disinfection procedure and biological-evaluation responsibilities.",
      "Drawing datums, machined interfaces, surface acceptance and required lot documentation.",
      "Prototype quantity, supplier qualification, change control, release authority and service requirements."
    ],
    "related": [
      {
        "href": "/products/composite-medical-support-profiles",
        "label": "Medical support profile component specification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom profile development"
      },
      {
        "href": "/applications/cfrp-robotic-beams-struts",
        "label": "Industrial motion structures and their different requirements"
      }
    ]
  },
  {
    "slug": "frp-scrubber-demister-profiles",
    "calculator": false,
    "lastModified": "2026-10-03",
    "title": "FRP Scrubber & Demister Profiles | Application Guide",
    "shortTitle": "Scrubber and demister profiles",
    "description": "Specify FRP scrubber vanes and demister supports: chemistry, flow, drainage, fouling, structural loads, washing, acceptance and regulatory scope.",
    "h1": "FRP profiles inside scrubbers and mist eliminators",
    "intro": "A corrosion-resistant profile must fit both a separation process and a load path. Define whether it captures droplets, locates a separator module or supports a packing bed before selecting its cross-section.",
    "environment": "F1 can assess constant-section glass-fiber composite profiles, support members, locator rails and approved secondary machining from an OEM or project drawing. Separator sizing, wash-system design, vessel integrity and emissions guarantees require the responsible equipment and plant designers.",
    "supplyScope": "F1 can assess constant-section glass-fiber composite profiles, support members, locator rails and approved secondary machining from an OEM or project drawing. Separator sizing, wash-system design, vessel integrity and emissions guarantees require the responsible equipment and plant designers.",
    "image": "/images/applications/guides/frp-scrubber-demister-profiles.svg",
    "imageAlt": "Vertical-flow vane-pack section with an open support grid, shell ledges, upward gas flow and downward liquid drainage.",
    "imageNote": "Application schematic",
    "imageCaption": "Gas passes through the vane pack while collected liquid drains downward; the carrier transfers pack loads to the shell ledges.",
    "recommendedProfiles": [
      "Custom constant-section lamella candidates",
      "Demister module support beams and frames",
      "Vane locator rails and spacer sections",
      "Packing-bed support members to an approved design"
    ],
    "resinSystem": "Select a documented glass-fiber laminate and resin for the complete gas, condensate, liquid and cleaning exposure schedule. Verify the surface system and any fire or electrostatic requirements on the actual construction.",
    "standards": [
      "VDI 3679 Part 3:2019-08",
      "ASTM C581-26 and ASTM D543-21",
      "ASTM D3917-23",
      "EN 13121-3:2016",
      "Air-emissions permits and monitoring conditions",
      "Directive 2014/34/EU (ATEX)",
      "IEC TS 60079-32-1:2013+A1:2017",
      "OSHA 29 CFR 1910.146 and 1910.147"
    ],
    "designChecks": [],
    "rfqInputs": [
      "Equipment tag, OEM, process description, plant location and replacement or new-build status.",
      "Component function and controlled drawings: vane geometry, support span, pitch, orientation, drains, hold-downs, seals and vessel interfaces.",
      "Gas flow at actual conditions, pressure, temperature, turndown, droplet/liquid loading, solids and allowed pressure loss.",
      "Exposure schedule: gas and liquid chemistry, concentration, normal/upset temperature, wet/dry periods, cleaning and abrasion.",
      "Design loads and allowable movement, including deposits, retained liquid, pressure differential and defined upset conditions.",
      "Material/fire/electrostatic requirements where applicable, with test methods and acceptance criteria.",
      "Manway and lifting constraints, module assembly sequence, inspection access and spare-part strategy.",
      "Component inspection plan, representative-module trial, OEM commissioning scope and plant performance-test responsibilities."
    ],
    "related": [
      {
        "href": "/products/frp-demister-support-profiles",
        "label": "Demister support profiles"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profiles"
      },
      {
        "href": "/applications/frp-pulp-paper-mill-components",
        "label": "Pulp and paper mill components"
      },
      {
        "href": "/applications/frp-wastewater-clarifier-components",
        "label": "Wastewater clarifier components"
      }
    ]
  }
];

export const specialistProductIndex = [
  {
    "slug": "frp-sludge-collector-flights",
    "name": "Sludge collector flights",
    "title": "FRP Sludge Collector Flights | Component Specification",
    "description": "Prepare a drawing-based inquiry for FRP collector flights: section geometry, drilling, wear-shoe interfaces, laminate evidence, tolerances and acceptance scope.",
    "image": "/images/applications/guides/frp-wastewater-clarifier-components.svg",
    "imageAlt": "Longitudinal clarifier section with separate flights on upper and lower chain runs, a sludge hopper, scum trough, fixed baffle and overflow weir."
  },
  {
    "slug": "frp-third-rail-coverboards",
    "name": "Pultruded third-rail coverboards",
    "title": "FRP Third-Rail Coverboards | Component Specification",
    "description": "Specify FRP third-rail coverboards with section geometry, bracket interfaces, material requirements, fabrication tolerances and batch acceptance evidence.",
    "image": "/images/applications/guides/frp-third-rail-protection.svg",
    "imageAlt": "Side-contact conductor rail on an insulating support beneath an FRP cover, with a separate cover bracket and collector shoe envelope."
  },
  {
    "slug": "fiberglass-live-line-tool-tubes-rods",
    "name": "Fiberglass insulating rod and tube components",
    "title": "Fiberglass Live-Line Tool Rods & Tubes | Specification",
    "description": "Specify fiberglass solid rods and foam-filled tubes for live-line tool development, covering geometry, interfaces, qualification and acceptance records.",
    "image": "/images/applications/guides/frp-live-line-tool-components.svg",
    "imageAlt": "Insulating component between metal fittings, with an exposed-section dimension and separate solid-rod and foam-filled-tube cross-sections."
  },
  {
    "slug": "pultruded-cfrp-strengthening-strips",
    "name": "Pultruded CFRP strengthening strips",
    "title": "Pultruded CFRP Strengthening Strips | Specification",
    "description": "Prepare a CFRP strip qualification inquiry with section geometry, laminate data, bonding-face requirements, batch evidence and system compatibility.",
    "image": "/images/applications/guides/cfrp-concrete-strengthening.svg",
    "imageAlt": "Simply supported concrete beam with downward loading, an adhesive layer, a soffit CFRP strip and marked end-transfer regions."
  },
  {
    "slug": "carbon-fiber-roller-tubes",
    "name": "Carbon-fibre roller tube components",
    "title": "Carbon-Fiber Roller Tubes | Component Procurement Guide",
    "description": "Specify CFRP roller tube geometry, reinforcement, machining allowances, end interfaces and inspection without assuming finished-roller qualification.",
    "image": "/images/applications/guides/carbon-fiber-industrial-rollers.svg",
    "imageAlt": "Axial roller section with bonded end plugs, journals and bearing supports, beside an end view of a tangent 90-degree web wrap."
  },
  {
    "slug": "fire-retardant-rail-profiles",
    "name": "Fire-retardant rail profile components",
    "title": "Fire-Retardant Rail Profiles | Component Specification",
    "description": "Prepare a railway profile inquiry with a controlled cross-section, material and finish schedule, fire-test coverage, first-article inspection and traceability.",
    "image": "/images/applications/guides/frp-rail-interior-profiles.svg",
    "imageAlt": "Rail interior section with secondary FRP supports attached to the carbody, bracket-mounted equipment and a retained ceiling panel."
  },
  {
    "slug": "frp-switchgear-insulating-profiles",
    "name": "Switchgear insulating profiles",
    "title": "FRP Switchgear Insulating Profiles | Qualification",
    "description": "Drawing-led inquiries for FRP switchgear support profiles and linkage blanks, with functional tolerances, material evidence, machining and release requirements.",
    "image": "/images/applications/guides/frp-switchgear-insulation-components.svg",
    "imageAlt": "Two switchgear details showing an FRP support between a metal frame and live busbar, and an insulating operating link between a moving contact and drive."
  },
  {
    "slug": "composite-conductor-core-rods",
    "name": "Composite conductor core development",
    "title": "Composite Conductor Core Rods | Development Inquiry",
    "description": "Plan a composite conductor core qualification inquiry: architecture, protected interfaces, reel handling, testing, traceability and conductor integration.",
    "image": "/images/applications/guides/composite-overhead-conductor-cores.svg",
    "imageAlt": "Conductor cross-section showing a central composite tensile core and two segmented aluminum layers."
  },
  {
    "slug": "carbon-fiber-robotic-beams",
    "name": "Carbon-fibre robotic beam components",
    "title": "Carbon-Fiber Robotic Beams | Component Specification",
    "description": "Prepare an OEM enquiry for carbon-fibre robot beams and struts, covering section geometry, reinforcement, end joints, tolerances and qualification evidence.",
    "image": "/images/applications/guides/cfrp-robotic-beams-struts.svg",
    "imageAlt": "Side elevation of a CFRP cantilever beam with a fixed root, bonded sleeve overlaps and a downward tool load."
  },
  {
    "slug": "composite-medical-support-profiles",
    "name": "Composite medical support profile components",
    "title": "Composite Medical Support Profiles | OEM Enquiries",
    "description": "Prepare a qualification enquiry for composite medical support profiles with controlled materials, interfaces, MR assessment, cleaning and OEM traceability.",
    "image": "/images/applications/guides/composite-mri-patient-supports.svg",
    "imageAlt": "Longitudinal MRI scanner section showing a patient table entering the open bore with housing clearance and pedestal support."
  },
  {
    "slug": "frp-demister-support-profiles",
    "name": "FRP demister support profiles",
    "title": "FRP Demister Support Profiles | Specification Guide",
    "description": "Plan FRP demister beams, locator rails and scrubber support profiles with defined geometry, chemistry, loading, machining and acceptance requirements.",
    "image": "/images/applications/guides/frp-scrubber-demister-profiles.svg",
    "imageAlt": "Vertical-flow vane-pack section with an open support grid, shell ledges, upward gas flow and downward liquid drainage."
  }
];

export const specialistApplicationGroups = [
  {
    "label": "Wastewater clarifier components",
    "description": "Specify pultruded FRP clarifier flights, weirs, scum baffles and supports, with guidance on mechanical interfaces, materials and acceptance standards.",
    "href": "/applications/frp-wastewater-clarifier-components",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/frp-sludge-collector-flights",
        "label": "Sludge collector flight specifications"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profiles"
      }
    ]
  },
  {
    "label": "Pulp and paper mill components",
    "description": "Plan pultruded FRP access and supports for pulp and paper mills. Review chemical exposure, connections, shutdown work, maintenance and workplace rules.",
    "href": "/applications/frp-pulp-paper-mill-components",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/frp-gratings",
        "label": "Pultruded grating"
      },
      {
        "href": "/products/frp-handrail-systems",
        "label": "Industrial handrail systems"
      }
    ]
  },
  {
    "label": "Dry-type transformer insulation supports",
    "description": "Specify pultruded fiberglass winding spacers and supports for dry-type transformers: thermal classes, contact loads, cooling, insulation and RFQ evidence.",
    "href": "/applications/frp-transformer-insulation-supports",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/fiberglass-dog-bone",
        "label": "Fiberglass dog-bone profile geometry"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profile development"
      }
    ]
  },
  {
    "label": "Third-rail protection systems",
    "description": "Plan pultruded third-rail coverboards around collector clearance, brackets, weather, fire requirements, electrical protection and operator qualification.",
    "href": "/applications/frp-third-rail-protection",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/frp-third-rail-coverboards",
        "label": "Specify a third-rail coverboard profile"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom section development"
      }
    ]
  },
  {
    "label": "Live-line tool component qualification",
    "description": "Develop a specification for fiberglass live-line tool rods and foam-filled tubes, separating component tests, complete-tool qualification and employer duties.",
    "href": "/applications/frp-live-line-tool-components",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/fiberglass-live-line-tool-tubes-rods",
        "label": "Specify insulating rod and tube components"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultrusion feasibility"
      }
    ]
  },
  {
    "label": "CFRP concrete strengthening",
    "description": "Specify pultruded CFRP strips for concrete strengthening: existing-structure assessment, bonding, installation controls, inspection and system qualification.",
    "href": "/applications/cfrp-concrete-strengthening",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/pultruded-cfrp-strengthening-strips",
        "label": "CFRP strip procurement and qualification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profile inquiries"
      }
    ]
  },
  {
    "label": "Carbon-fibre industrial rollers",
    "description": "Define carbon roller requirements for film, printing and nonwoven lines: load paths, rotor behaviour, surfaces, end fittings, commissioning and qualification.",
    "href": "/applications/carbon-fiber-industrial-rollers",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/carbon-fiber-roller-tubes",
        "label": "Roller-tube procurement and qualification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom component inquiries"
      }
    ]
  },
  {
    "label": "Rail interior and secondary profiles",
    "description": "Plan railway interior and secondary pultruded profiles with a defined component function, EN 45545 fire evidence, connections, traceability and change control.",
    "href": "/applications/frp-rail-interior-profiles",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/fire-retardant-rail-profiles",
        "label": "Rail-profile procurement and qualification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom profile development"
      }
    ]
  },
  {
    "label": "Switchgear insulation and mechanism components",
    "description": "Specify pultruded FRP switchgear supports and operating parts: insulation paths, fault loads, cycling, thermal duty, material tests and OEM qualification.",
    "href": "/applications/frp-switchgear-insulation-components",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/frp-switchgear-insulating-profiles",
        "label": "Switchgear insulating profile specification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profile development"
      }
    ]
  },
  {
    "label": "Composite cores for overhead conductors",
    "description": "Evaluate composite cores for overhead conductors: material architecture, heat and creep, bending, fittings, sag-tension, installation and qualification.",
    "href": "/applications/composite-overhead-conductor-cores",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/composite-conductor-core-rods",
        "label": "Composite conductor core development inquiry"
      }
    ]
  },
  {
    "label": "CFRP robotic beams and struts",
    "description": "Specify carbon-fibre robot beams and struts: stiffness, joints, buckling, fatigue, positioning, machine safety and a staged component qualification plan.",
    "href": "/applications/cfrp-robotic-beams-struts",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/carbon-fiber-robotic-beams",
        "label": "Carbon-fibre beam component specification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profiles"
      }
    ]
  },
  {
    "label": "Composite MRI patient supports",
    "description": "Define composite MRI patient-support requirements: GFRP or CFRP selection, load paths, MR assessment, cleaning, traceability and OEM device qualification.",
    "href": "/applications/composite-mri-patient-supports",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/composite-medical-support-profiles",
        "label": "Medical support profile component specification"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom profile development"
      }
    ]
  },
  {
    "label": "Scrubber and demister profiles",
    "description": "Specify FRP scrubber vanes and demister supports: chemistry, flow, drainage, fouling, structural loads, washing, acceptance and regulatory scope.",
    "href": "/applications/frp-scrubber-demister-profiles",
    "products": [
      "custom"
    ],
    "links": [
      {
        "href": "/products/frp-demister-support-profiles",
        "label": "Demister support profiles"
      },
      {
        "href": "/products/custom-pultruded-profiles",
        "label": "Custom pultruded profiles"
      }
    ]
  }
];

export const specialistGuideRoutes = [
  "/applications/frp-wastewater-clarifier-components",
  "/applications/frp-pulp-paper-mill-components",
  "/products/frp-sludge-collector-flights",
  "/applications/frp-transformer-insulation-supports",
  "/applications/frp-third-rail-protection",
  "/applications/frp-live-line-tool-components",
  "/products/frp-third-rail-coverboards",
  "/products/fiberglass-live-line-tool-tubes-rods",
  "/applications/cfrp-concrete-strengthening",
  "/applications/carbon-fiber-industrial-rollers",
  "/applications/frp-rail-interior-profiles",
  "/products/pultruded-cfrp-strengthening-strips",
  "/products/carbon-fiber-roller-tubes",
  "/products/fire-retardant-rail-profiles",
  "/applications/frp-switchgear-insulation-components",
  "/products/frp-switchgear-insulating-profiles",
  "/applications/composite-overhead-conductor-cores",
  "/products/composite-conductor-core-rods",
  "/applications/cfrp-robotic-beams-struts",
  "/products/carbon-fiber-robotic-beams",
  "/applications/composite-mri-patient-supports",
  "/products/composite-medical-support-profiles",
  "/applications/frp-scrubber-demister-profiles",
  "/products/frp-demister-support-profiles"
];
