#!/usr/bin/env python3
"""Build the English procurement catalog from the website's windowSystems.json.
Requires reportlab. Run from any directory; output URL remains stable.
Illustrations are source-catalog assets, not engineering drawings or test evidence.
"""
import json
from pathlib import Path
from xml.sax.saxutils import escape
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak

ROOT=Path(__file__).resolve().parents[1]
DATA=json.loads((ROOT/'content/data/windowSystems.json').read_text())
OUT=ROOT/'public/downloads/f1composite-frp-window-door-catalog.pdf'
BLUE=colors.HexColor('#031697'); TEAL=colors.HexColor('#00A199'); YELLOW=colors.HexColor('#FFD400')
INK=colors.HexColor('#202B40'); GREY=colors.HexColor('#536078'); PALE=colors.HexColor('#F0F4F8')
W,H=A4
ST={
 'body':ParagraphStyle('body',fontName='Helvetica',fontSize=10.5,leading=15,textColor=INK,spaceAfter=9),
 'small':ParagraphStyle('small',fontName='Helvetica',fontSize=8.5,leading=12,textColor=GREY,spaceAfter=7),
 'title':ParagraphStyle('title',fontName='Helvetica-Bold',fontSize=24,leading=28,textColor=BLUE,spaceAfter=15),
 'h2':ParagraphStyle('h2',fontName='Helvetica-Bold',fontSize=15,leading=20,textColor=BLUE,spaceBefore=12,spaceAfter=9),
 'eye':ParagraphStyle('eye',fontName='Courier-Bold',fontSize=9,leading=13,textColor=TEAL,spaceAfter=9),
 'cell':ParagraphStyle('cell',fontName='Helvetica',fontSize=9,leading=12,textColor=INK),
 'head':ParagraphStyle('head',fontName='Helvetica-Bold',fontSize=9,leading=12,textColor=colors.white),
}
def p(s,style='body'):return Paragraph(s,ST[style])
def table(rows,widths):
 t=Table([[p(escape(str(c)),'head' if i==0 else 'cell') for c in row] for i,row in enumerate(rows)],colWidths=[v*mm for v in widths],repeatRows=1,hAlign='LEFT')
 t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),BLUE),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,PALE]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),9),('RIGHTPADDING',(0,0),(-1,-1),9),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]))
 return t

def footer(c,doc):
 c.saveState();c.setStrokeColor(TEAL);c.setLineWidth(1);c.line(19*mm,280*mm,191*mm,280*mm)
 c.setFillColor(BLUE);c.setFont('Helvetica-Bold',9);c.drawString(19*mm,284*mm,'F1 COMPOSITE')
 c.setFillColor(GREY);c.setFont('Courier',7);c.drawRightString(191*mm,284*mm,'WINDOW & DOOR SYSTEMS / '+DATA['revision'])
 c.setFont('Helvetica',8);c.drawString(19*mm,12*mm,'f1composite.com  |  Chongqing, China');c.drawRightString(191*mm,12*mm,str(doc.page));c.restoreState()
def newpage(eye,title):return [PageBreak(),p(eye,'eye'),p(title,'title')]
def contact():return [p('Doris Li | Sales','h2'),p('Doris.li@f1composite.com | +86 138 8333 8993'),p('Technical: f1frp2015@gmail.com'),p('www.f1composite.com/contact')]

story=[p('PRODUCT SELECTION + PROCUREMENT / SEPTEMBER 2026','eye'),p('FRP Window &amp;<br/>Door Systems','title'),p('System profiles for local fabrication.<br/>Finished windows and doors for project supply.'),Image(str(ROOT/'public/images/products/window-systems/70.jpg'),width=90*mm,height=90*mm),p('Choose your supply route','h2'),table([['System profiles - primary route','Finished units - independent route'],['Select compatible sections, lengths and quantities. Review drawings, interfaces and local fabrication before production.','Submit a window schedule. Confirm dimensions, opening, glazing, hardware and delivery scope before manufacture.']],[86,86]),Spacer(1,8*mm),p('Nine systems | Current profile-code index | Two RFQ templates','eye'),p('Catalog references support initial selection. Drawings, evidence and commercial scope are confirmed for each order.','small')]+contact()
story+=newpage('01 / COMPARE SYSTEMS','Build a technical shortlist')
story+=[p('Begin with the required opening and purchasing route. Frame depth alone does not determine thermal performance, structural capacity or project compliance.'),table([['System','Frame depth','Reference wall','Profile codes']]+[[s['id'],str(s['depthMm'])+' mm',str(s['wallThicknessMm'])+' mm',s['profiles'][0]['code']+' - '+s['profiles'][-1]['code']] for s in DATA['series']],[34,35,35,68]),Spacer(1,7*mm),p('How to read the data','h2'),p(DATA['sourceNote']),p('Uf = frame thermal transmittance. Ug = glass thermal transmittance. Uw = complete-window thermal transmittance. Compare only identified configurations under the same method.'),p('Reference leaf loads shown on the following pages are catalog entries, not approved ratings. Hardware, leaf size, glass weight, reinforcement and testing must be reviewed together.','small')]
for i,s in enumerate(DATA['series']):
 story+=newpage('02 / SYSTEM REFERENCE / '+s['id'].upper(),escape(s['name']))
 story+=[p(escape(s['summary'])),Image(str(ROOT/'public'/s['image'].lstrip('/')),width=52*mm,height=52*mm),p('Source-catalog corner illustration. Assembly concept only; not a dimensioned drawing.','small'),table([['Frame depth reference','Wall reference','Leaf-load reference'],[str(s['depthMm'])+' mm',str(s['wallThicknessMm'])+' mm',str(s['referenceMaxLeafKg'])+' kg - configuration review']],[57,57,58]),p('Opening options','h2'),p(escape('; '.join(s['openingTypes']))+'. Final compatibility requires the approved assembly.'),p('Current profile index','h2'),table([['Current code','Component / drawing status','Ref. kg/m']]+[[q['code'],q['label'],q.get('referenceKgM','Confirm')] for q in s['profiles']],[31,111,30])]
 if s['id']=='140':story+=[p('Legacy mapping: CP006/GF0801; CP007/GF0802; CP008/GF0803; CP009/GF0804; CP010/GF0805; CP011/GF0806. Legacy codes apply only to the old 140 drawings; current GF08 codes belong to the 55 system. Former inward-opening component names require assembly confirmation.','small')]
 if s['id']=='90-sliding':story+=[p('CP001-CP005 are current code positions. Component names and section drawings remain to be confirmed; the old three-section index is not a substitute.','small')]
 story+=[p('Quote by series + current code + drawing revision. Catalog mass, dimensions and leaf load are conditional references; production availability, tolerances and tested configurations require confirmation. Source: July 2026 catalog, profile index PDF 9 and system PDF '+str(11+i//2)+'.','small')]
story+=newpage('03 / ACCESSORIES + CUSTOM DEVELOPMENT','Define the complete interface')
story+=[p('Subframes / installation profiles','h2'),Image(str(ROOT/'public/images/products/window-systems/subframes.jpg'),width=172*mm,height=42*mm),p('Source-catalog subframe illustrations; size designations require approved dimensional drawings.','small'),table([['Subframe designation','Confirm before ordering']]+[[s['label'],'Wall thickness, tolerances, fastening, drainage and frame/wall interfaces'] for s in DATA['subframes']],[55,117]),p('Confirm each supply item','h2'),p('Main frame and sash profiles form the window system. Subframes connect the unit to the opening. Beads, seals, corner connectors, hardware, glass and fabrication services must each appear in the agreed supply list. Cross-series interchangeability is not assumed.'),p('Custom window-system development','h2'),p('Provide section drawings or interface requirements, target performance, material and finish preferences, fabrication method, development stage and annual demand. Review feasibility, tooling, samples and validation scope before committing production quantities.'),p('Source: July 2026 catalog PDF 19. Illustration dimensions are not machining or installation instructions.','small')]
story+=newpage('04 / BUY SYSTEM PROFILES','From section selection to repeat supply')
story+=[p('For fabricators, OEMs and profile distributors. Start with the series or a drawing; early technical enquiries do not require a complete BOM.'),table([['Stage','Buyer prepares','Review / deliverable'],['1. Application','Opening, destination, target duty','Candidate system and missing information'],['2. Drawing review','Codes, revision, interfaces, tolerances','Compatible-section list and technical clarifications'],['3. Scope and quotation','Lengths, quantities, finish, accessories','Itemized scope, samples, tooling and freight'],['4. Samples','Short section / corner / sample window','Appearance, interfaces or assembly checks'],['5. Fabrication validation','Machining, joining, glass and hardware','Agreed trial and performance-validation plan'],['6. Pilot order','Approved revision, packing, acceptance','First-batch inspection and release criteria'],['7. Repeat supply','Forecast, batch feedback, change requests','Controlled revisions and reorder scope']],[29,68,75]),p('Samples answer different questions','h2'),p('Short sections show material, finish and section shape. Corner samples demonstrate joint and interface concepts. Sample windows support assembly and specified testing. Pilot batches assess the agreed production and supply process. A section sample does not establish whole-window performance.'),p('RFQ checklist','h2'),p('Series and current code; drawing revision; cut length and unit; quantity per section; finish; accessory scope; sample stage; destination; target date. Add critical tolerances and local fabrication capability where known.'),p('Download: f1-window-profile-bom-template.csv','eye')]
story+=newpage('05 / BUY FINISHED UNITS','From window schedule to site delivery')
story+=[p('For project purchasers, importers and finished-unit distributors. Quote each window or door mark against a defined configuration.'),table([['Stage','Buyer prepares','Review / deliverable'],['1. Project review','Destination, use, project requirements','Configuration options and evidence gaps'],['2. Window schedule','Mark, width, height, units, quantity','Opening-size vs finished-frame-size clarification'],['3. Configuration','Opening, glass, hardware, colors','Specified configuration and evidence scope'],['4. Quotation','Delivery point, date, batches','Price per mark plus explicit inclusions'],['5. Approval','Checked dimensions and shop drawings','Frozen schedule and production revision'],['6. Inspection','Acceptance and sampling requirements','Agreed inspection and identification records'],['7. Packing / delivery','Receiver, unloading and site limits','Crate/mark mapping and shipping documents'],['8. Installation / support','Local installer, wall interface, receipt check','Agreed installation information and spare parts']],[29,68,75]),p('Separate the delivery milestones','h2'),p('Factory release, arrival at port, site delivery, unloading and installation completion are different events. Confirm freight, unloading, site installation, local testing and after-sales responsibilities in the order.'),p('Download: f1-window-schedule-template.csv','eye'),p('A budget enquiry may start with approximate quantities. A production quotation requires checked dimensions, opening direction, configuration and supply scope.','small')]
story+=newpage('06 / EVIDENCE + RFQ','Send the information you have')
story+=[p('Choose profiles or finished units, identify the series if known, and tell us whether you need technical selection, samples, a budget or a formal quotation.'),p('Match evidence to the purchase','h2'),table([['Evidence level','What to identify'],['Profile / material','Section and revision, resin, dimensions, tolerances, finish and applicable material evidence'],['Complete window / door','Series, specimen size, opening, glazing, seals, hardware and test/calculation method'],['Project / installation','Destination requirements, mounting detail, installation responsibilities and acceptance criteria']],[48,124]),Spacer(1,5*mm),p('A report for one specimen does not certify all sizes or series. Historical lift-sliding reports retain their original product identity and are not automatically evidence for the current 140 compression-seal configuration.'),p('Include these files where available','h2'),p('Profiles: PDF/DWG/DXF drawings and a CSV/XLSX BOM.<br/>Finished units: CSV/XLSX window schedule, PDF drawings and relevant site details.<br/>Both: destination, quantity, expected date, sample needs and target performance.'),p('Confirm before production','h2'),p('Drawing and schedule revision; current codes; dimensions and units; accessory and glass scope; finish; acceptance plan; packing; delivery terms; local installation; spare parts and after-sales responsibilities.'),p('Source and edition','h2'),p('Product references and original corner illustrations: July 2026 source catalog, PDF pages 9, 11-15 and 19. Code mapping and current 140 name: approved September 2026 product review. This English F1 edition presents purchasing information, not a replacement for approved engineering drawings.','small')]+contact()
OUT.parent.mkdir(parents=True,exist_ok=True)
SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=19*mm,leftMargin=19*mm,topMargin=26*mm,bottomMargin=22*mm,title='F1 Composite FRP Window & Door Systems',author='F1 Composite').build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)
